import {
    Globe,
    Search,
    MapPin,
    ShieldCheck,
    FileText,
    Activity,
    Hash,
    FileCode,
    Key,
    Lock,
    KeyRound,
    Link,
    MonitorSmartphone,
    Server,
    Type,
    Link2,
    Palette,
    ArrowLeftRight,
    ListFilter,
    Globe2,
    FileJson,
    Code,
    Binary,
    SeparatorHorizontal,
    PenTool,
    AlignLeft,
    Thermometer,
    Gauge,
    HardDrive,
    Mail,
    Scissors,
    FileSpreadsheet, // Added for Table/Excel tools
    Database, // Added for SQL tools
    Files, // Added for PDF tools
    Image as ImageIcon,
    FileDown,
    Disc, // Added for Spin Wheel
} from 'lucide-react'

export type ModuleCategory = 'Network' | 'Utilities' | 'General' | 'Table' | 'JSON' | 'CSV' | 'Markdown' | 'HTML' | 'SQL' | 'LaTeX' | 'XML' | 'MySQL' | 'MediaWiki' | 'PDF'

export interface Module {
    key: string
    name: string
    description: string
    href: string
    icon: any
    category: ModuleCategory
    permission?: string
    isNew?: boolean
    isPopular?: boolean
}

export const modules: Module[] = [
    {
        key: 'dns-lookup',
        name: 'DNS Lookup',
        description: 'Tra cứu thông tin DNS (A, MX, NS, TXT...) của tên miền nhanh chóng.',
        href: '/tools/dns-lookup',
        icon: Globe,
        category: 'Network',
        isNew: true,
        isPopular: true
    },
    {
        key: 'ip-lookup',
        name: 'IP Lookup',
        description: 'Tra cứu thông tin địa chỉ IP (ISP, Vị trí, ASN) chi tiết.',
        href: '/tools/ip-lookup',
        icon: MapPin,
        category: 'Network',
        isNew: true,
        isPopular: true
    },
    {
        key: 'ssl-lookup',
        name: 'SSL Lookup',
        description: 'Kiểm tra thông tin chứng chỉ SSL/TLS và thời hạn sử dụng.',
        href: '/tools/ssl-lookup',
        icon: ShieldCheck,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'whois-lookup',
        name: 'Whois Lookup',
        description: 'Kiểm tra thông tin tên miền, ngày đăng ký và nhà cung cấp.',
        href: '/tools/whois-lookup',
        icon: FileText,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'spin-wheel',
        name: 'Spin Wheel',
        description: 'Công cụ quay số ngẫu nhiên để chọn một mục từ danh sách.',
        href: '/tools/spin-wheel',
        icon: Disc,
        category: 'Utilities',
        isNew: true,
    },
    {
        key: 'ping-tool',
        name: 'Ping & Port',
        description: 'Kiểm tra trạng thái Website (HTTP Ping) và Open Port.',
        href: '/tools/ping',
        icon: Activity,
        category: 'Network',
        isNew: true
    },
    {
        key: 'md5-generator',
        name: 'MD5 Generator',
        description: 'Công cụ tạo mã MD5 Hash nhanh chóng.',
        href: '/tools/md5-generator',
        icon: Hash,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'base64-converter',
        name: 'Base64 Converter',
        description: 'Mã hóa và giải mã Base64 (Encode/Decode).',
        href: '/tools/base64-converter',
        icon: FileCode,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'markdown-to-html',
        name: 'Markdown to HTML',
        description: 'Chuyển đổi Markdown sang HTML với Live Preview.',
        href: '/tools/markdown-to-html',
        icon: FileCode,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'uuid-generator',
        name: 'UUID Generator',
        description: 'Tạo mã UUID v4 ngẫu nhiên (Bulk supported).',
        href: '/tools/uuid-generator',
        icon: Key,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'bcrypt-generator',
        name: 'Bcrypt Generator',
        description: 'Tạo mã băm Bcrypt và kiểm tra mật khẩu.',
        href: '/tools/bcrypt-generator',
        icon: Lock,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'spin-wheel',
        name: 'Spin Wheel',
        description: 'Công cụ quay số ngẫu nhiên để chọn một mục từ danh sách.',
        href: '/tools/spin-wheel',
        icon: Disc,
        category: 'Utilities',
        isNew: true,
        isPopular: true
    },
    {
        key: 'password-generator',
        name: 'Password Generator',
        description: 'Tạo mật khẩu mạnh ngẫu nhiên (Strong Password).',
        href: '/tools/password-generator',
        icon: KeyRound,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'slug-generator',
        name: 'Slug Generator',
        description: 'Tạo URL Slug thân thiện SEO từ văn bản.',
        href: '/tools/slug-generator',
        icon: Link,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'html-minifier',
        name: 'HTML Minifier',
        description: 'Tối ưu hóa và nén mã HTML (remove whitespace/comments).',
        href: '/tools/html-minifier',
        icon: FileCode,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'css-minifier',
        name: 'CSS Minifier',
        description: 'Nén mã CSS/StyleSheet để tối ưu tốc độ tải trang.',
        href: '/tools/css-minifier',
        icon: FileCode, // Or Palette if imported
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'js-minifier',
        name: 'JS Minifier',
        description: 'Nén và tối ưu mã JavaScript (Basic Minification).',
        href: '/tools/js-minifier',
        icon: FileCode, // Or Braces if imported
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'user-agent-parser',
        name: 'User Agent Parser',
        description: 'Phân tích chuỗi User Agent để lấy thông tin thiết bị, OS, Browser.',
        href: '/tools/user-agent-parser',
        icon: MonitorSmartphone,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'hosting-checker',
        name: 'Hosting Checker',
        description: 'Kiểm tra nhà cung cấp Hosting (ISP) và vị trí máy chủ của website.',
        href: '/tools/hosting-checker',
        icon: Server,
        category: 'Network',
        isNew: true
    },
    {
        key: 'character-counter',
        name: 'Character Counter',
        description: 'Đếm số ký tự, từ, câu, đoạn văn trong văn bản.',
        href: '/tools/character-counter',
        icon: Type,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'url-parser',
        name: 'URL Parser',
        description: 'Phân tích URL thành các thành phần: Protocol, Host, Path, Query Params...',
        href: '/tools/url-parser',
        icon: Link2,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'color-converter',
        name: 'Color Converter',
        description: 'Chuyển đổi mã màu giữa các định dạng Hex, RGB, HSL, CMYK.',
        href: '/tools/color-converter',
        icon: Palette,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'http-header-lookup',
        name: 'HTTP Header Lookup',
        description: 'Kiểm tra HTTP Response Headers và Status Code.',
        href: '/tools/http-header-lookup',
        icon: ArrowLeftRight,
        category: 'Network',
        isNew: true
    },
    {
        key: 'duplicate-lines-remover',
        name: 'Duplicate Lines Remover',
        description: 'Lọc và xóa các dòng trùng lặp trong danh sách.',
        href: '/tools/duplicate-lines-remover',
        icon: ListFilter,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'idn-punycode-converter',
        name: 'IDN Punycode Converter',
        description: 'Chuyển đổi tên miền quốc tế (IDN) sang Punycode và ngược lại.',
        href: '/tools/idn-punycode-converter',
        icon: Globe2,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'json-validator',
        name: 'JSON Validator',
        description: 'Kiểm tra, định dạng (Beautify) và nén (Minify) mã JSON.',
        href: '/tools/json-validator',
        icon: FileJson,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'meta-tag-checker',
        name: 'Meta Tag Checker',
        description: 'Phân tích thẻ Meta, SEO và Social Media.',
        href: '/tools/meta-tag-checker',
        icon: Search,
        category: 'Network',
        isNew: true
    },
    {
        key: 'sql-formatter',
        name: 'SQL Formatter',
        description: 'Định dạng và làm đẹp câu lệnh SQL (Beautify).',
        href: '/tools/sql-formatter',
        icon: Server, // Reuse Server or Database if imported, else fallback
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'html-entity-converter',
        name: 'HTML Entity Converter',
        description: 'Chuyển đổi ký tự đặc biệt sang HTML Entities.',
        href: '/tools/html-entity-converter',
        icon: Code,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'binary-converter',
        name: 'Binary Converter',
        description: 'Chuyển đổi văn bản sang nhị phân (010101).',
        href: '/tools/binary-converter',
        icon: Binary,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'text-separator',
        name: 'Text Separator',
        description: 'Tách hoặc gộp danh sách văn bản theo ký tự.',
        href: '/tools/text-separator',
        icon: SeparatorHorizontal,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'hex-converter',
        name: 'Hex Converter',
        description: 'Chuyển đổi Hex, Decimal và Text.',
        href: '/tools/hex-converter',
        icon: Hash,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'signature-generator',
        name: 'Signature Generator',
        description: 'Tạo chữ ký điện tử (Digital Signature) online.',
        href: '/tools/signature-generator',
        icon: PenTool,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'lorem-ipsum-generator',
        name: 'Lorem Ipsum Generator',
        description: 'Tạo văn bản giả (Dummy Text) Lorem Ipsum.',
        href: '/tools/lorem-ipsum-generator',
        icon: AlignLeft,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'temperature-converter',
        name: 'Temperature Converter',
        description: 'Chuyển đổi nhiệt độ (Celsius, Fahrenheit, Kelvin).',
        href: '/tools/temperature-converter',
        icon: Thermometer,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'speed-converter',
        name: 'Speed Converter',
        description: 'Chuyển đổi vận tốc (MPH <-> KPH).',
        href: '/tools/speed-converter',
        icon: Gauge,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'roman-numeral-converter',
        name: 'Roman Numeral Converter',
        description: 'Chuyển đổi số La Mã (Roman Numerals) và số tự nhiên.',
        href: '/tools/roman-numeral-converter',
        icon: Hash, // Reusing Hash or bring in Type/Hash
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'data-converter',
        name: 'Data Unit Converter',
        description: 'Chuyển đổi đơn vị dữ liệu (Bits, Bytes, KB, MB, GB, TB, KiB, MiB...).',
        href: '/tools/data-converter',
        icon: HardDrive,
        category: 'Utilities',
        isNew: true
    },
    {
        key: 'shortlinks',
        name: 'Shortlinks',
        description: 'Tạo và quản lý URL rút gọn với mật khẩu bảo vệ và thời gian hết hạn.',
        href: '/dashboard/shortlinks',
        icon: Scissors,
        category: 'Utilities',
        isNew: true,
        isPopular: true
    },
    {
        key: 'mail-system',
        name: 'Mail System',
        description: 'Gửi email qua SMTP, quản lý tài khoản và theo dõi lịch sử gửi mail.',
        href: '/dashboard/mail',
        icon: Mail,
        category: 'Utilities',
        isNew: true,
        isPopular: true
    },
    {
        key: 'merge-pdf',
        name: 'Merge PDF',
        description: 'Ghép nhiều file PDF thành một file duy nhất.',
        href: '/tools/merge-pdf',
        icon: Files, // Using Files icon for PDF
        category: 'PDF',
        isNew: true,
        isPopular: true
    },
    {
        key: 'split-pdf',
        name: 'Split PDF',
        description: 'Chia nhỏ file PDF hoặc trích xuất các trang cụ thể.',
        href: '/tools/split-pdf',
        icon: Scissors,
        category: 'PDF',
        isNew: true,
        isPopular: true
    },
    {
        key: 'pdf-to-image',
        name: 'PDF to Image',
        description: 'Chuyển đổi các trang PDF thành hình ảnh (PNG).',
        href: '/tools/pdf-to-image',
        icon: ImageIcon,
        category: 'PDF',
        isNew: true,
        isPopular: true
    },
    {
        key: 'image-to-pdf',
        name: 'Image to PDF',
        description: 'Chuyển đổi hình ảnh (PNG, JPG) thành file PDF.',
        href: '/tools/image-to-pdf',
        icon: FileDown,
        category: 'PDF',
        isNew: true,
        isPopular: true
    },
    // Table Converters
    { key: 'excel-to-actionscript', name: 'Excel to ActionScript', description: 'Convert Excel to ActionScript.', href: '/tools/excel-to-actionscript', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-ascii', name: 'Excel to ASCII', description: 'Convert Excel to ASCII Table.', href: '/tools/excel-to-ascii', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-asciidoc', name: 'Excel to AsciiDoc', description: 'Convert Excel to AsciiDoc.', href: '/tools/excel-to-asciidoc', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-asp', name: 'Excel to ASP', description: 'Convert Excel to ASP.', href: '/tools/excel-to-asp', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-avro', name: 'Excel to Avro', description: 'Convert Excel to Avro.', href: '/tools/excel-to-avro', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-bbcode', name: 'Excel to BBCode', description: 'Convert Excel to BBCode.', href: '/tools/excel-to-bbcode', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-csv', name: 'Excel to CSV', description: 'Convert Excel to CSV.', href: '/tools/excel-to-csv', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-dax', name: 'Excel to DAX', description: 'Convert Excel to DAX.', href: '/tools/excel-to-dax', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-excel', name: 'Excel to Excel', description: 'Check/Validate Excel format.', href: '/tools/excel-to-excel', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-firebase', name: 'Excel to Firebase', description: 'Convert Excel to Firebase JSON.', href: '/tools/excel-to-firebase', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-html', name: 'Excel to HTML', description: 'Convert Excel to HTML Table.', href: '/tools/excel-to-html', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-ini', name: 'Excel to INI', description: 'Convert Excel to INI.', href: '/tools/excel-to-ini', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-jira', name: 'Excel to Jira', description: 'Convert Excel to Jira markup.', href: '/tools/excel-to-jira', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-jpeg', name: 'Excel to JPEG', description: 'Convert Excel sheet to JPEG image.', href: '/tools/excel-to-jpeg', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-json', name: 'Excel to JSON', description: 'Convert Excel to JSON.', href: '/tools/excel-to-json', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-jsonlines', name: 'Excel to JSON Lines', description: 'Convert Excel to JSON Lines.', href: '/tools/excel-to-jsonlines', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-latex', name: 'Excel to LaTeX', description: 'Convert Excel to LaTeX.', href: '/tools/excel-to-latex', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-magic', name: 'Excel to Magic', description: 'Convert Excel to Magic.', href: '/tools/excel-to-magic', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-markdown', name: 'Excel to Markdown', description: 'Convert Excel to Markdown Table.', href: '/tools/excel-to-markdown', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-matlab', name: 'Excel to MATLAB', description: 'Convert Excel to MATLAB.', href: '/tools/excel-to-matlab', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-mediawiki', name: 'Excel to MediaWiki', description: 'Convert Excel to MediaWiki Table.', href: '/tools/excel-to-mediawiki', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-pandasdataframe', name: 'Excel to Pandas', description: 'Convert Excel to Pandas DataFrame code.', href: '/tools/excel-to-pandasdataframe', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-pdf', name: 'Excel to PDF', description: 'Convert Excel to PDF.', href: '/tools/excel-to-pdf', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-php', name: 'Excel to PHP', description: 'Convert Excel to PHP Array.', href: '/tools/excel-to-php', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-png', name: 'Excel to PNG', description: 'Convert Excel sheet to PNG image.', href: '/tools/excel-to-png', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-protobuf', name: 'Excel to Protobuf', description: 'Convert Excel to Protobuf.', href: '/tools/excel-to-protobuf', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-qlik', name: 'Excel to Qlik', description: 'Convert Excel to Qlik.', href: '/tools/excel-to-qlik', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-rdataframe', name: 'Excel to R DataFrame', description: 'Convert Excel to R DataFrame.', href: '/tools/excel-to-rdataframe', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-rdf', name: 'Excel to RDF', description: 'Convert Excel to RDF.', href: '/tools/excel-to-rdf', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-restructuredtext', name: 'Excel to reStructuredText', description: 'Convert Excel to reStructuredText.', href: '/tools/excel-to-restructuredtext', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-ruby', name: 'Excel to Ruby', description: 'Convert Excel to Ruby Array.', href: '/tools/excel-to-ruby', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-sql', name: 'Excel to SQL', description: 'Convert Excel to SQL Insert Queries.', href: '/tools/excel-to-sql', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-textile', name: 'Excel to Textile', description: 'Convert Excel to Textile.', href: '/tools/excel-to-textile', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-toml', name: 'Excel to TOML', description: 'Convert Excel to TOML.', href: '/tools/excel-to-toml', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-tracwiki', name: 'Excel to TracWiki', description: 'Convert Excel to TracWiki.', href: '/tools/excel-to-tracwiki', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-xml', name: 'Excel to XML', description: 'Convert Excel to XML.', href: '/tools/excel-to-xml', icon: FileSpreadsheet, category: 'Table' },
    { key: 'excel-to-yaml', name: 'Excel to YAML', description: 'Convert Excel to YAML.', href: '/tools/excel-to-yaml', icon: FileSpreadsheet, category: 'Table' },
    // JSON Converters
    { key: 'json-to-actionscript', name: 'JSON to ActionScript', description: 'Convert JSON to ActionScript.', href: '/tools/json-to-actionscript', icon: FileJson, category: 'JSON' },
    { key: 'json-to-ascii', name: 'JSON to ASCII', description: 'Convert JSON to ASCII Table.', href: '/tools/json-to-ascii', icon: FileJson, category: 'JSON' },
    { key: 'json-to-asciidoc', name: 'JSON to AsciiDoc', description: 'Convert JSON to AsciiDoc.', href: '/tools/json-to-asciidoc', icon: FileJson, category: 'JSON' },
    { key: 'json-to-asp', name: 'JSON to ASP', description: 'Convert JSON to ASP.', href: '/tools/json-to-asp', icon: FileJson, category: 'JSON' },
    { key: 'json-to-avro', name: 'JSON to Avro', description: 'Convert JSON to Avro.', href: '/tools/json-to-avro', icon: FileJson, category: 'JSON' },
    { key: 'json-to-bbcode', name: 'JSON to BBCode', description: 'Convert JSON to BBCode.', href: '/tools/json-to-bbcode', icon: FileJson, category: 'JSON' },
    { key: 'json-to-csv', name: 'JSON to CSV', description: 'Convert JSON to CSV.', href: '/tools/json-to-csv', icon: FileJson, category: 'JSON' },
    { key: 'json-to-dax', name: 'JSON to DAX', description: 'Convert JSON to DAX.', href: '/tools/json-to-dax', icon: FileJson, category: 'JSON' },
    { key: 'json-to-excel', name: 'JSON to Excel', description: 'Convert JSON to Excel.', href: '/tools/json-to-excel', icon: FileJson, category: 'JSON' },
    { key: 'json-to-firebase', name: 'JSON to Firebase', description: 'Convert JSON to Firebase.', href: '/tools/json-to-firebase', icon: FileJson, category: 'JSON' },
    { key: 'json-to-html', name: 'JSON to HTML', description: 'Convert JSON to HTML Table.', href: '/tools/json-to-html', icon: FileJson, category: 'JSON' },
    { key: 'json-to-ini', name: 'JSON to INI', description: 'Convert JSON to INI.', href: '/tools/json-to-ini', icon: FileJson, category: 'JSON' },
    { key: 'json-to-jira', name: 'JSON to Jira', description: 'Convert JSON to Jira markup.', href: '/tools/json-to-jira', icon: FileJson, category: 'JSON' },
    { key: 'json-to-jpeg', name: 'JSON to JPEG', description: 'Convert JSON to JPEG image.', href: '/tools/json-to-jpeg', icon: FileJson, category: 'JSON' },
    { key: 'json-to-json', name: 'JSON to JSON', description: 'Validate and Format JSON.', href: '/tools/json-to-json', icon: FileJson, category: 'JSON' },
    { key: 'json-to-jsonlines', name: 'JSON to JSON Lines', description: 'Convert JSON to JSON Lines.', href: '/tools/json-to-jsonlines', icon: FileJson, category: 'JSON' },
    { key: 'json-to-latex', name: 'JSON to LaTeX', description: 'Convert JSON to LaTeX.', href: '/tools/json-to-latex', icon: FileJson, category: 'JSON' },
    { key: 'json-to-magic', name: 'JSON to Magic', description: 'Convert JSON to Magic.', href: '/tools/json-to-magic', icon: FileJson, category: 'JSON' },
    { key: 'json-to-markdown', name: 'JSON to Markdown', description: 'Convert JSON to Markdown Table.', href: '/tools/json-to-markdown', icon: FileJson, category: 'JSON' },
    { key: 'json-to-matlab', name: 'JSON to MATLAB', description: 'Convert JSON to MATLAB.', href: '/tools/json-to-matlab', icon: FileJson, category: 'JSON' },
    { key: 'json-to-mediawiki', name: 'JSON to MediaWiki', description: 'Convert JSON to MediaWiki Table.', href: '/tools/json-to-mediawiki', icon: FileJson, category: 'JSON' },
    { key: 'json-to-pandasdataframe', name: 'JSON to Pandas', description: 'Convert JSON to Pandas DataFrame.', href: '/tools/json-to-pandasdataframe', icon: FileJson, category: 'JSON' },
    { key: 'json-to-pdf', name: 'JSON to PDF', description: 'Convert JSON to PDF.', href: '/tools/json-to-pdf', icon: FileJson, category: 'JSON' },
    { key: 'json-to-php', name: 'JSON to PHP', description: 'Convert JSON to PHP Array.', href: '/tools/json-to-php', icon: FileJson, category: 'JSON' },
    { key: 'json-to-png', name: 'JSON to PNG', description: 'Convert JSON to PNG image.', href: '/tools/json-to-png', icon: FileJson, category: 'JSON' },
    { key: 'json-to-protobuf', name: 'JSON to Protobuf', description: 'Convert JSON to Protobuf.', href: '/tools/json-to-protobuf', icon: FileJson, category: 'JSON' },
    { key: 'json-to-qlik', name: 'JSON to Qlik', description: 'Convert JSON to Qlik.', href: '/tools/json-to-qlik', icon: FileJson, category: 'JSON' },
    { key: 'json-to-rdataframe', name: 'JSON to R DataFrame', description: 'Convert JSON to R DataFrame.', href: '/tools/json-to-rdataframe', icon: FileJson, category: 'JSON' },
    { key: 'json-to-rdf', name: 'JSON to RDF', description: 'Convert JSON to RDF.', href: '/tools/json-to-rdf', icon: FileJson, category: 'JSON' },
    { key: 'json-to-restructuredtext', name: 'JSON to reStructuredText', description: 'Convert JSON to reStructuredText.', href: '/tools/json-to-restructuredtext', icon: FileJson, category: 'JSON' },
    { key: 'json-to-ruby', name: 'JSON to Ruby', description: 'Convert JSON to Ruby.', href: '/tools/json-to-ruby', icon: FileJson, category: 'JSON' },
    { key: 'json-to-sql', name: 'JSON to SQL', description: 'Convert JSON to SQL.', href: '/tools/json-to-sql', icon: FileJson, category: 'JSON' },
    { key: 'json-to-textile', name: 'JSON to Textile', description: 'Convert JSON to Textile.', href: '/tools/json-to-textile', icon: FileJson, category: 'JSON' },
    { key: 'json-to-toml', name: 'JSON to TOML', description: 'Convert JSON to TOML.', href: '/tools/json-to-toml', icon: FileJson, category: 'JSON' },
    { key: 'json-to-tracwiki', name: 'JSON to TracWiki', description: 'Convert JSON to TracWiki.', href: '/tools/json-to-tracwiki', icon: FileJson, category: 'JSON' },
    { key: 'json-to-xml', name: 'JSON to XML', description: 'Convert JSON to XML.', href: '/tools/json-to-xml', icon: FileJson, category: 'JSON' },
    { key: 'json-to-yaml', name: 'JSON to YAML', description: 'Convert JSON to YAML.', href: '/tools/json-to-yaml', icon: FileJson, category: 'JSON' },
    // CSV Converters
    { key: 'csv-to-actionscript', name: 'CSV to ActionScript', description: 'Convert CSV to ActionScript.', href: '/tools/csv-to-actionscript', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-ascii', name: 'CSV to ASCII', description: 'Convert CSV to ASCII Table.', href: '/tools/csv-to-ascii', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-asciidoc', name: 'CSV to AsciiDoc', description: 'Convert CSV to AsciiDoc.', href: '/tools/csv-to-asciidoc', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-asp', name: 'CSV to ASP', description: 'Convert CSV to ASP.', href: '/tools/csv-to-asp', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-avro', name: 'CSV to Avro', description: 'Convert CSV to Avro.', href: '/tools/csv-to-avro', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-bbcode', name: 'CSV to BBCode', description: 'Convert CSV to BBCode.', href: '/tools/csv-to-bbcode', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-csv', name: 'CSV to CSV', description: 'Format and Clean CSV.', href: '/tools/csv-to-csv', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-dax', name: 'CSV to DAX', description: 'Convert CSV to DAX.', href: '/tools/csv-to-dax', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-excel', name: 'CSV to Excel', description: 'Convert CSV to Excel.', href: '/tools/csv-to-excel', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-firebase', name: 'CSV to Firebase', description: 'Convert CSV to Firebase.', href: '/tools/csv-to-firebase', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-html', name: 'CSV to HTML', description: 'Convert CSV to HTML Table.', href: '/tools/csv-to-html', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-ini', name: 'CSV to INI', description: 'Convert CSV to INI.', href: '/tools/csv-to-ini', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-jira', name: 'CSV to Jira', description: 'Convert CSV to Jira markup.', href: '/tools/csv-to-jira', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-jpeg', name: 'CSV to JPEG', description: 'Convert CSV to JPEG image.', href: '/tools/csv-to-jpeg', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-json', name: 'CSV to JSON', description: 'Convert CSV to JSON.', href: '/tools/csv-to-json', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-jsonlines', name: 'CSV to JSON Lines', description: 'Convert CSV to JSON Lines.', href: '/tools/csv-to-jsonlines', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-latex', name: 'CSV to LaTeX', description: 'Convert CSV to LaTeX.', href: '/tools/csv-to-latex', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-magic', name: 'CSV to Magic', description: 'Convert CSV to Magic.', href: '/tools/csv-to-magic', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-markdown', name: 'CSV to Markdown', description: 'Convert CSV to Markdown Table.', href: '/tools/csv-to-markdown', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-matlab', name: 'CSV to MATLAB', description: 'Convert CSV to MATLAB.', href: '/tools/csv-to-matlab', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-mediawiki', name: 'CSV to MediaWiki', description: 'Convert CSV to MediaWiki Table.', href: '/tools/csv-to-mediawiki', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-pandasdataframe', name: 'CSV to Pandas', description: 'Convert CSV to Pandas DataFrame.', href: '/tools/csv-to-pandasdataframe', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-pdf', name: 'CSV to PDF', description: 'Convert CSV to PDF.', href: '/tools/csv-to-pdf', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-php', name: 'CSV to PHP', description: 'Convert CSV to PHP Array.', href: '/tools/csv-to-php', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-png', name: 'CSV to PNG', description: 'Convert CSV to PNG image.', href: '/tools/csv-to-png', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-protobuf', name: 'CSV to Protobuf', description: 'Convert CSV to Protobuf.', href: '/tools/csv-to-protobuf', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-qlik', name: 'CSV to Qlik', description: 'Convert CSV to Qlik.', href: '/tools/csv-to-qlik', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-rdataframe', name: 'CSV to R DataFrame', description: 'Convert CSV to R DataFrame.', href: '/tools/csv-to-rdataframe', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-rdf', name: 'CSV to RDF', description: 'Convert CSV to RDF.', href: '/tools/csv-to-rdf', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-restructuredtext', name: 'CSV to reStructuredText', description: 'Convert CSV to reStructuredText.', href: '/tools/csv-to-restructuredtext', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-ruby', name: 'CSV to Ruby', description: 'Convert CSV to Ruby.', href: '/tools/csv-to-ruby', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-sql', name: 'CSV to SQL', description: 'Convert CSV to SQL.', href: '/tools/csv-to-sql', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-textile', name: 'CSV to Textile', description: 'Convert CSV to Textile.', href: '/tools/csv-to-textile', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-toml', name: 'CSV to TOML', description: 'Convert CSV to TOML.', href: '/tools/csv-to-toml', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-tracwiki', name: 'CSV to TracWiki', description: 'Convert CSV to TracWiki.', href: '/tools/csv-to-tracwiki', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-xml', name: 'CSV to XML', description: 'Convert CSV to XML.', href: '/tools/csv-to-xml', icon: FileSpreadsheet, category: 'CSV' },
    { key: 'csv-to-yaml', name: 'CSV to YAML', description: 'Convert CSV to YAML.', href: '/tools/csv-to-yaml', icon: FileSpreadsheet, category: 'CSV' },
    // Markdown Converters
    { key: 'markdown-to-actionscript', name: 'Markdown to ActionScript', description: 'Convert Markdown to ActionScript.', href: '/tools/markdown-to-actionscript', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-ascii', name: 'Markdown to ASCII', description: 'Convert Markdown to ASCII.', href: '/tools/markdown-to-ascii', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-asciidoc', name: 'Markdown to AsciiDoc', description: 'Convert Markdown to AsciiDoc.', href: '/tools/markdown-to-asciidoc', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-asp', name: 'Markdown to ASP', description: 'Convert Markdown to ASP.', href: '/tools/markdown-to-asp', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-avro', name: 'Markdown to Avro', description: 'Convert Markdown to Avro.', href: '/tools/markdown-to-avro', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-bbcode', name: 'Markdown to BBCode', description: 'Convert Markdown to BBCode.', href: '/tools/markdown-to-bbcode', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-csv', name: 'Markdown to CSV', description: 'Convert Markdown Table to CSV.', href: '/tools/markdown-to-csv', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-dax', name: 'Markdown to DAX', description: 'Convert Markdown to DAX.', href: '/tools/markdown-to-dax', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-excel', name: 'Markdown to Excel', description: 'Convert Markdown Table to Excel.', href: '/tools/markdown-to-excel', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-firebase', name: 'Markdown to Firebase', description: 'Convert Markdown to Firebase.', href: '/tools/markdown-to-firebase', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-html', name: 'Markdown to HTML', description: 'Convert Markdown to HTML.', href: '/tools/markdown-to-html', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-ini', name: 'Markdown to INI', description: 'Convert Markdown to INI.', href: '/tools/markdown-to-ini', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-jira', name: 'Markdown to Jira', description: 'Convert Markdown to Jira.', href: '/tools/markdown-to-jira', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-jpeg', name: 'Markdown to JPEG', description: 'Convert Markdown to JPEG (Image).', href: '/tools/markdown-to-jpeg', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-json', name: 'Markdown to JSON', description: 'Convert Markdown Table to JSON.', href: '/tools/markdown-to-json', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-jsonlines', name: 'Markdown to JSON Lines', description: 'Convert Markdown to JSON Lines.', href: '/tools/markdown-to-jsonlines', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-latex', name: 'Markdown to LaTeX', description: 'Convert Markdown to LaTeX.', href: '/tools/markdown-to-latex', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-magic', name: 'Markdown to Magic', description: 'Convert Markdown to Magic.', href: '/tools/markdown-to-magic', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-markdown', name: 'Markdown to Markdown', description: 'Beautify/Format Markdown.', href: '/tools/markdown-to-markdown', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-matlab', name: 'Markdown to MATLAB', description: 'Convert Markdown to MATLAB.', href: '/tools/markdown-to-matlab', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-mediawiki', name: 'Markdown to MediaWiki', description: 'Convert Markdown to MediaWiki.', href: '/tools/markdown-to-mediawiki', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-pandasdataframe', name: 'Markdown to Pandas', description: 'Convert Markdown Table to Pandas.', href: '/tools/markdown-to-pandasdataframe', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-pdf', name: 'Markdown to PDF', description: 'Convert Markdown to PDF.', href: '/tools/markdown-to-pdf', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-php', name: 'Markdown to PHP', description: 'Convert Markdown to PHP.', href: '/tools/markdown-to-php', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-png', name: 'Markdown to PNG', description: 'Convert Markdown to PNG (Image).', href: '/tools/markdown-to-png', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-protobuf', name: 'Markdown to Protobuf', description: 'Convert Markdown to Protobuf.', href: '/tools/markdown-to-protobuf', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-qlik', name: 'Markdown to Qlik', description: 'Convert Markdown to Qlik.', href: '/tools/markdown-to-qlik', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-rdataframe', name: 'Markdown to R DataFrame', description: 'Convert Markdown to R DataFrame.', href: '/tools/markdown-to-rdataframe', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-rdf', name: 'Markdown to RDF', description: 'Convert Markdown to RDF.', href: '/tools/markdown-to-rdf', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-restructuredtext', name: 'Markdown to reStructuredText', description: 'Convert Markdown to reStructuredText.', href: '/tools/markdown-to-restructuredtext', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-ruby', name: 'Markdown to Ruby', description: 'Convert Markdown to Ruby.', href: '/tools/markdown-to-ruby', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-sql', name: 'Markdown to SQL', description: 'Convert Markdown Table to SQL.', href: '/tools/markdown-to-sql', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-textile', name: 'Markdown to Textile', description: 'Convert Markdown to Textile.', href: '/tools/markdown-to-textile', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-toml', name: 'Markdown to TOML', description: 'Convert Markdown to TOML.', href: '/tools/markdown-to-toml', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-tracwiki', name: 'Markdown to TracWiki', description: 'Convert Markdown to TracWiki.', href: '/tools/markdown-to-tracwiki', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-xml', name: 'Markdown to XML', description: 'Convert Markdown to XML.', href: '/tools/markdown-to-xml', icon: FileCode, category: 'Markdown' },
    { key: 'markdown-to-yaml', name: 'Markdown to YAML', description: 'Convert Markdown to YAML.', href: '/tools/markdown-to-yaml', icon: FileCode, category: 'Markdown' },
    // HTML Converters
    { key: 'html-to-actionscript', name: 'HTML to ActionScript', description: 'Convert HTML to ActionScript.', href: '/tools/html-to-actionscript', icon: FileCode, category: 'HTML' },
    { key: 'html-to-ascii', name: 'HTML to ASCII', description: 'Convert HTML to ASCII.', href: '/tools/html-to-ascii', icon: FileCode, category: 'HTML' },
    { key: 'html-to-asciidoc', name: 'HTML to AsciiDoc', description: 'Convert HTML to AsciiDoc.', href: '/tools/html-to-asciidoc', icon: FileCode, category: 'HTML' },
    { key: 'html-to-asp', name: 'HTML to ASP', description: 'Convert HTML to ASP.', href: '/tools/html-to-asp', icon: FileCode, category: 'HTML' },
    { key: 'html-to-avro', name: 'HTML to Avro', description: 'Convert HTML to Avro.', href: '/tools/html-to-avro', icon: FileCode, category: 'HTML' },
    { key: 'html-to-bbcode', name: 'HTML to BBCode', description: 'Convert HTML to BBCode.', href: '/tools/html-to-bbcode', icon: FileCode, category: 'HTML' },
    { key: 'html-to-csv', name: 'HTML to CSV', description: 'Convert HTML Table to CSV.', href: '/tools/html-to-csv', icon: FileCode, category: 'HTML' },
    { key: 'html-to-dax', name: 'HTML to DAX', description: 'Convert HTML to DAX.', href: '/tools/html-to-dax', icon: FileCode, category: 'HTML' },
    { key: 'html-to-excel', name: 'HTML to Excel', description: 'Convert HTML Table to Excel.', href: '/tools/html-to-excel', icon: FileCode, category: 'HTML' },
    { key: 'html-to-firebase', name: 'HTML to Firebase', description: 'Convert HTML to Firebase.', href: '/tools/html-to-firebase', icon: FileCode, category: 'HTML' },
    { key: 'html-to-html', name: 'HTML to HTML', description: 'Beautify/Format HTML.', href: '/tools/html-to-html', icon: FileCode, category: 'HTML' },
    { key: 'html-to-ini', name: 'HTML to INI', description: 'Convert HTML to INI.', href: '/tools/html-to-ini', icon: FileCode, category: 'HTML' },
    { key: 'html-to-jira', name: 'HTML to Jira', description: 'Convert HTML to Jira.', href: '/tools/html-to-jira', icon: FileCode, category: 'HTML' },
    { key: 'html-to-jpeg', name: 'HTML to JPEG', description: 'Convert HTML to JPEG (Image).', href: '/tools/html-to-jpeg', icon: FileCode, category: 'HTML' },
    { key: 'html-to-json', name: 'HTML to JSON', description: 'Convert HTML Table to JSON.', href: '/tools/html-to-json', icon: FileCode, category: 'HTML' },
    { key: 'html-to-jsonlines', name: 'HTML to JSON Lines', description: 'Convert HTML to JSON Lines.', href: '/tools/html-to-jsonlines', icon: FileCode, category: 'HTML' },
    { key: 'html-to-latex', name: 'HTML to LaTeX', description: 'Convert HTML to LaTeX.', href: '/tools/html-to-latex', icon: FileCode, category: 'HTML' },
    { key: 'html-to-magic', name: 'HTML to Magic', description: 'Convert HTML to Magic.', href: '/tools/html-to-magic', icon: FileCode, category: 'HTML' },
    { key: 'html-to-markdown', name: 'HTML to Markdown', description: 'Convert HTML to Markdown.', href: '/tools/html-to-markdown', icon: FileCode, category: 'HTML' },
    { key: 'html-to-matlab', name: 'HTML to MATLAB', description: 'Convert HTML to MATLAB.', href: '/tools/html-to-matlab', icon: FileCode, category: 'HTML' },
    { key: 'html-to-mediawiki', name: 'HTML to MediaWiki', description: 'Convert HTML to MediaWiki.', href: '/tools/html-to-mediawiki', icon: FileCode, category: 'HTML' },
    { key: 'html-to-pandasdataframe', name: 'HTML to Pandas', description: 'Convert HTML Table to Pandas.', href: '/tools/html-to-pandasdataframe', icon: FileCode, category: 'HTML' },
    { key: 'html-to-pdf', name: 'HTML to PDF', description: 'Convert HTML to PDF.', href: '/tools/html-to-pdf', icon: FileCode, category: 'HTML' },
    { key: 'html-to-php', name: 'HTML to PHP', description: 'Convert HTML to PHP.', href: '/tools/html-to-php', icon: FileCode, category: 'HTML' },
    { key: 'html-to-png', name: 'HTML to PNG', description: 'Convert HTML to PNG (Image).', href: '/tools/html-to-png', icon: FileCode, category: 'HTML' },
    { key: 'html-to-protobuf', name: 'HTML to Protobuf', description: 'Convert HTML to Protobuf.', href: '/tools/html-to-protobuf', icon: FileCode, category: 'HTML' },
    { key: 'html-to-qlik', name: 'HTML to Qlik', description: 'Convert HTML to Qlik.', href: '/tools/html-to-qlik', icon: FileCode, category: 'HTML' },
    { key: 'html-to-rdataframe', name: 'HTML to R DataFrame', description: 'Convert HTML to R DataFrame.', href: '/tools/html-to-rdataframe', icon: FileCode, category: 'HTML' },
    { key: 'html-to-rdf', name: 'HTML to RDF', description: 'Convert HTML to RDF.', href: '/tools/html-to-rdf', icon: FileCode, category: 'HTML' },
    { key: 'html-to-restructuredtext', name: 'HTML to reStructuredText', description: 'Convert HTML to reStructuredText.', href: '/tools/html-to-restructuredtext', icon: FileCode, category: 'HTML' },
    { key: 'html-to-ruby', name: 'HTML to Ruby', description: 'Convert HTML to Ruby.', href: '/tools/html-to-ruby', icon: FileCode, category: 'HTML' },
    { key: 'html-to-sql', name: 'HTML to SQL', description: 'Convert HTML Table to SQL.', href: '/tools/html-to-sql', icon: FileCode, category: 'HTML' },
    { key: 'html-to-textile', name: 'HTML to Textile', description: 'Convert HTML to Textile.', href: '/tools/html-to-textile', icon: FileCode, category: 'HTML' },
    { key: 'html-to-toml', name: 'HTML to TOML', description: 'Convert HTML to TOML.', href: '/tools/html-to-toml', icon: FileCode, category: 'HTML' },
    { key: 'html-to-tracwiki', name: 'HTML to TracWiki', description: 'Convert HTML to TracWiki.', href: '/tools/html-to-tracwiki', icon: FileCode, category: 'HTML' },
    { key: 'html-to-xml', name: 'HTML to XML', description: 'Convert HTML to XML.', href: '/tools/html-to-xml', icon: FileCode, category: 'HTML' },
    { key: 'html-to-yaml', name: 'HTML to YAML', description: 'Convert HTML to YAML.', href: '/tools/html-to-yaml', icon: FileCode, category: 'HTML' },
    // SQL Converters
    { key: 'sql-to-actionscript', name: 'SQL to ActionScript', description: 'Convert SQL to ActionScript.', href: '/tools/sql-to-actionscript', icon: Database, category: 'SQL' },
    { key: 'sql-to-ascii', name: 'SQL to ASCII', description: 'Convert SQL to ASCII.', href: '/tools/sql-to-ascii', icon: Database, category: 'SQL' },
    { key: 'sql-to-asciidoc', name: 'SQL to AsciiDoc', description: 'Convert SQL to AsciiDoc.', href: '/tools/sql-to-asciidoc', icon: Database, category: 'SQL' },
    { key: 'sql-to-asp', name: 'SQL to ASP', description: 'Convert SQL to ASP.', href: '/tools/sql-to-asp', icon: Database, category: 'SQL' },
    { key: 'sql-to-avro', name: 'SQL to Avro', description: 'Convert SQL to Avro.', href: '/tools/sql-to-avro', icon: Database, category: 'SQL' },
    { key: 'sql-to-bbcode', name: 'SQL to BBCode', description: 'Convert SQL to BBCode.', href: '/tools/sql-to-bbcode', icon: Database, category: 'SQL' },
    { key: 'sql-to-csv', name: 'SQL to CSV', description: 'Convert SQL to CSV.', href: '/tools/sql-to-csv', icon: Database, category: 'SQL' },
    { key: 'sql-to-dax', name: 'SQL to DAX', description: 'Convert SQL to DAX.', href: '/tools/sql-to-dax', icon: Database, category: 'SQL' },
    { key: 'sql-to-excel', name: 'SQL to Excel', description: 'Convert SQL to Excel.', href: '/tools/sql-to-excel', icon: Database, category: 'SQL' },
    { key: 'sql-to-firebase', name: 'SQL to Firebase', description: 'Convert SQL to Firebase.', href: '/tools/sql-to-firebase', icon: Database, category: 'SQL' },
    { key: 'sql-to-html', name: 'SQL to HTML', description: 'Convert SQL to HTML.', href: '/tools/sql-to-html', icon: Database, category: 'SQL' },
    { key: 'sql-to-ini', name: 'SQL to INI', description: 'Convert SQL to INI.', href: '/tools/sql-to-ini', icon: Database, category: 'SQL' },
    { key: 'sql-to-jira', name: 'SQL to Jira', description: 'Convert SQL to Jira.', href: '/tools/sql-to-jira', icon: Database, category: 'SQL' },
    { key: 'sql-to-jpeg', name: 'SQL to JPEG', description: 'Convert SQL to JPEG (Image).', href: '/tools/sql-to-jpeg', icon: Database, category: 'SQL' },
    { key: 'sql-to-json', name: 'SQL to JSON', description: 'Convert SQL to JSON.', href: '/tools/sql-to-json', icon: Database, category: 'SQL' },
    { key: 'sql-to-jsonlines', name: 'SQL to JSON Lines', description: 'Convert SQL to JSON Lines.', href: '/tools/sql-to-jsonlines', icon: Database, category: 'SQL' },
    { key: 'sql-to-latex', name: 'SQL to LaTeX', description: 'Convert SQL to LaTeX.', href: '/tools/sql-to-latex', icon: Database, category: 'SQL' },
    { key: 'sql-to-magic', name: 'SQL to Magic', description: 'Convert SQL to Magic.', href: '/tools/sql-to-magic', icon: Database, category: 'SQL' },
    { key: 'sql-to-markdown', name: 'SQL to Markdown', description: 'Convert SQL to Markdown.', href: '/tools/sql-to-markdown', icon: Database, category: 'SQL' },
    { key: 'sql-to-matlab', name: 'SQL to MATLAB', description: 'Convert SQL to MATLAB.', href: '/tools/sql-to-matlab', icon: Database, category: 'SQL' },
    { key: 'sql-to-mediawiki', name: 'SQL to MediaWiki', description: 'Convert SQL to MediaWiki.', href: '/tools/sql-to-mediawiki', icon: Database, category: 'SQL' },
    { key: 'sql-to-pandasdataframe', name: 'SQL to Pandas', description: 'Convert SQL to Pandas.', href: '/tools/sql-to-pandasdataframe', icon: Database, category: 'SQL' },
    { key: 'sql-to-pdf', name: 'SQL to PDF', description: 'Convert SQL to PDF.', href: '/tools/sql-to-pdf', icon: Database, category: 'SQL' },
    { key: 'sql-to-php', name: 'SQL to PHP', description: 'Convert SQL to PHP.', href: '/tools/sql-to-php', icon: Database, category: 'SQL' },
    { key: 'sql-to-png', name: 'SQL to PNG', description: 'Convert SQL to PNG (Image).', href: '/tools/sql-to-png', icon: Database, category: 'SQL' },
    { key: 'sql-to-protobuf', name: 'SQL to Protobuf', description: 'Convert SQL to Protobuf.', href: '/tools/sql-to-protobuf', icon: Database, category: 'SQL' },
    { key: 'sql-to-qlik', name: 'SQL to Qlik', description: 'Convert SQL to Qlik.', href: '/tools/sql-to-qlik', icon: Database, category: 'SQL' },
    { key: 'sql-to-rdataframe', name: 'SQL to R DataFrame', description: 'Convert SQL to R DataFrame.', href: '/tools/sql-to-rdataframe', icon: Database, category: 'SQL' },
    { key: 'sql-to-rdf', name: 'SQL to RDF', description: 'Convert SQL to RDF.', href: '/tools/sql-to-rdf', icon: Database, category: 'SQL' },
    { key: 'sql-to-restructuredtext', name: 'SQL to reStructuredText', description: 'Convert SQL to reStructuredText.', href: '/tools/sql-to-restructuredtext', icon: Database, category: 'SQL' },
    { key: 'sql-to-ruby', name: 'SQL to Ruby', description: 'Convert SQL to Ruby.', href: '/tools/sql-to-ruby', icon: Database, category: 'SQL' },
    { key: 'sql-to-sql', name: 'SQL to SQL', description: 'Format/Clean SQL.', href: '/tools/sql-to-sql', icon: Database, category: 'SQL' },
    { key: 'sql-to-textile', name: 'SQL to Textile', description: 'Convert SQL to Textile.', href: '/tools/sql-to-textile', icon: Database, category: 'SQL' },
    { key: 'sql-to-toml', name: 'SQL to TOML', description: 'Convert SQL to TOML.', href: '/tools/sql-to-toml', icon: Database, category: 'SQL' },
    { key: 'sql-to-tracwiki', name: 'SQL to TracWiki', description: 'Convert SQL to TracWiki.', href: '/tools/sql-to-tracwiki', icon: Database, category: 'SQL' },
    { key: 'sql-to-xml', name: 'SQL to XML', description: 'Convert SQL to XML.', href: '/tools/sql-to-xml', icon: Database, category: 'SQL' },
    { key: 'sql-to-yaml', name: 'SQL to YAML', description: 'Convert SQL to YAML.', href: '/tools/sql-to-yaml', icon: Database, category: 'SQL' },

    // LaTeX Converters
    { key: 'latex-to-actionscript', name: 'LaTeX to ActionScript', description: 'Convert LaTeX to ActionScript.', href: '/tools/latex-to-actionscript', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-ascii', name: 'LaTeX to ASCII', description: 'Convert LaTeX to ASCII.', href: '/tools/latex-to-ascii', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-asciidoc', name: 'LaTeX to AsciiDoc', description: 'Convert LaTeX to AsciiDoc.', href: '/tools/latex-to-asciidoc', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-asp', name: 'LaTeX to ASP', description: 'Convert LaTeX to ASP.', href: '/tools/latex-to-asp', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-avro', name: 'LaTeX to Avro', description: 'Convert LaTeX to Avro.', href: '/tools/latex-to-avro', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-bbcode', name: 'LaTeX to BBCode', description: 'Convert LaTeX to BBCode.', href: '/tools/latex-to-bbcode', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-csv', name: 'LaTeX to CSV', description: 'Convert LaTeX Table to CSV.', href: '/tools/latex-to-csv', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-dax', name: 'LaTeX to DAX', description: 'Convert LaTeX to DAX.', href: '/tools/latex-to-dax', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-excel', name: 'LaTeX to Excel', description: 'Convert LaTeX Table to Excel.', href: '/tools/latex-to-excel', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-firebase', name: 'LaTeX to Firebase', description: 'Convert LaTeX to Firebase.', href: '/tools/latex-to-firebase', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-html', name: 'LaTeX to HTML', description: 'Convert LaTeX to HTML.', href: '/tools/latex-to-html', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-ini', name: 'LaTeX to INI', description: 'Convert LaTeX to INI.', href: '/tools/latex-to-ini', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-jira', name: 'LaTeX to Jira', description: 'Convert LaTeX to Jira.', href: '/tools/latex-to-jira', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-jpeg', name: 'LaTeX to JPEG', description: 'Convert LaTeX to JPEG (Image).', href: '/tools/latex-to-jpeg', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-json', name: 'LaTeX to JSON', description: 'Convert LaTeX Table to JSON.', href: '/tools/latex-to-json', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-jsonlines', name: 'LaTeX to JSON Lines', description: 'Convert LaTeX to JSON Lines.', href: '/tools/latex-to-jsonlines', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-latex', name: 'LaTeX to LaTeX', description: 'Format/Beautify LaTeX.', href: '/tools/latex-to-latex', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-magic', name: 'LaTeX to Magic', description: 'Convert LaTeX to Magic.', href: '/tools/latex-to-magic', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-markdown', name: 'LaTeX to Markdown', description: 'Convert LaTeX to Markdown.', href: '/tools/latex-to-markdown', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-matlab', name: 'LaTeX to MATLAB', description: 'Convert LaTeX to MATLAB.', href: '/tools/latex-to-matlab', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-mediawiki', name: 'LaTeX to MediaWiki', description: 'Convert LaTeX to MediaWiki.', href: '/tools/latex-to-mediawiki', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-pandasdataframe', name: 'LaTeX to Pandas', description: 'Convert LaTeX Table to Pandas.', href: '/tools/latex-to-pandasdataframe', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-pdf', name: 'LaTeX to PDF', description: 'Convert LaTeX to PDF.', href: '/tools/latex-to-pdf', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-php', name: 'LaTeX to PHP', description: 'Convert LaTeX to PHP.', href: '/tools/latex-to-php', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-png', name: 'LaTeX to PNG', description: 'Convert LaTeX to PNG (Image).', href: '/tools/latex-to-png', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-protobuf', name: 'LaTeX to Protobuf', description: 'Convert LaTeX to Protobuf.', href: '/tools/latex-to-protobuf', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-qlik', name: 'LaTeX to Qlik', description: 'Convert LaTeX to Qlik.', href: '/tools/latex-to-qlik', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-rdataframe', name: 'LaTeX to R DataFrame', description: 'Convert LaTeX to R DataFrame.', href: '/tools/latex-to-rdataframe', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-rdf', name: 'LaTeX to RDF', description: 'Convert LaTeX to RDF.', href: '/tools/latex-to-rdf', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-restructuredtext', name: 'LaTeX to reStructuredText', description: 'Convert LaTeX to reStructuredText.', href: '/tools/latex-to-restructuredtext', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-ruby', name: 'LaTeX to Ruby', description: 'Convert LaTeX to Ruby.', href: '/tools/latex-to-ruby', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-sql', name: 'LaTeX to SQL', description: 'Convert LaTeX Table to SQL.', href: '/tools/latex-to-sql', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-textile', name: 'LaTeX to Textile', description: 'Convert LaTeX to Textile.', href: '/tools/latex-to-textile', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-toml', name: 'LaTeX to TOML', description: 'Convert LaTeX to TOML.', href: '/tools/latex-to-toml', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-tracwiki', name: 'LaTeX to TracWiki', description: 'Convert LaTeX to TracWiki.', href: '/tools/latex-to-tracwiki', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-xml', name: 'LaTeX to XML', description: 'Convert LaTeX to XML.', href: '/tools/latex-to-xml', icon: FileCode, category: 'LaTeX' },
    { key: 'latex-to-yaml', name: 'LaTeX to YAML', description: 'Convert LaTeX to YAML.', href: '/tools/latex-to-yaml', icon: FileCode, category: 'LaTeX' },

    // XML Converters
    { key: 'xml-to-actionscript', name: 'XML to ActionScript', description: 'Convert XML to ActionScript.', href: '/tools/xml-to-actionscript', icon: FileCode, category: 'XML' },
    { key: 'xml-to-ascii', name: 'XML to ASCII', description: 'Convert XML to ASCII.', href: '/tools/xml-to-ascii', icon: FileCode, category: 'XML' },
    { key: 'xml-to-asciidoc', name: 'XML to AsciiDoc', description: 'Convert XML to AsciiDoc.', href: '/tools/xml-to-asciidoc', icon: FileCode, category: 'XML' },
    { key: 'xml-to-asp', name: 'XML to ASP', description: 'Convert XML to ASP.', href: '/tools/xml-to-asp', icon: FileCode, category: 'XML' },
    { key: 'xml-to-avro', name: 'XML to Avro', description: 'Convert XML to Avro.', href: '/tools/xml-to-avro', icon: FileCode, category: 'XML' },
    { key: 'xml-to-bbcode', name: 'XML to BBCode', description: 'Convert XML to BBCode.', href: '/tools/xml-to-bbcode', icon: FileCode, category: 'XML' },
    { key: 'xml-to-csv', name: 'XML to CSV', description: 'Convert XML to CSV.', href: '/tools/xml-to-csv', icon: FileCode, category: 'XML' },
    { key: 'xml-to-dax', name: 'XML to DAX', description: 'Convert XML to DAX.', href: '/tools/xml-to-dax', icon: FileCode, category: 'XML' },
    { key: 'xml-to-excel', name: 'XML to Excel', description: 'Convert XML to Excel.', href: '/tools/xml-to-excel', icon: FileCode, category: 'XML' },
    { key: 'xml-to-firebase', name: 'XML to Firebase', description: 'Convert XML to Firebase.', href: '/tools/xml-to-firebase', icon: FileCode, category: 'XML' },
    { key: 'xml-to-html', name: 'XML to HTML', description: 'Convert XML to HTML.', href: '/tools/xml-to-html', icon: FileCode, category: 'XML' },
    { key: 'xml-to-ini', name: 'XML to INI', description: 'Convert XML to INI.', href: '/tools/xml-to-ini', icon: FileCode, category: 'XML' },
    { key: 'xml-to-jira', name: 'XML to Jira', description: 'Convert XML to Jira.', href: '/tools/xml-to-jira', icon: FileCode, category: 'XML' },
    { key: 'xml-to-jpeg', name: 'XML to JPEG', description: 'Convert XML to JPEG (Image).', href: '/tools/xml-to-jpeg', icon: FileCode, category: 'XML' },
    { key: 'xml-to-json', name: 'XML to JSON', description: 'Convert XML to JSON.', href: '/tools/xml-to-json', icon: FileCode, category: 'XML' },
    { key: 'xml-to-jsonlines', name: 'XML to JSON Lines', description: 'Convert XML to JSON Lines.', href: '/tools/xml-to-jsonlines', icon: FileCode, category: 'XML' },
    { key: 'xml-to-latex', name: 'XML to LaTeX', description: 'Convert XML to LaTeX.', href: '/tools/xml-to-latex', icon: FileCode, category: 'XML' },
    { key: 'xml-to-magic', name: 'XML to Magic', description: 'Convert XML to Magic.', href: '/tools/xml-to-magic', icon: FileCode, category: 'XML' },
    { key: 'xml-to-markdown', name: 'XML to Markdown', description: 'Convert XML to Markdown.', href: '/tools/xml-to-markdown', icon: FileCode, category: 'XML' },
    { key: 'xml-to-matlab', name: 'XML to MATLAB', description: 'Convert XML to MATLAB.', href: '/tools/xml-to-matlab', icon: FileCode, category: 'XML' },
    { key: 'xml-to-mediawiki', name: 'XML to MediaWiki', description: 'Convert XML to MediaWiki.', href: '/tools/xml-to-mediawiki', icon: FileCode, category: 'XML' },
    { key: 'xml-to-pandasdataframe', name: 'XML to Pandas', description: 'Convert XML to Pandas.', href: '/tools/xml-to-pandasdataframe', icon: FileCode, category: 'XML' },
    { key: 'xml-to-pdf', name: 'XML to PDF', description: 'Convert XML to PDF.', href: '/tools/xml-to-pdf', icon: FileCode, category: 'XML' },
    { key: 'xml-to-php', name: 'XML to PHP', description: 'Convert XML to PHP.', href: '/tools/xml-to-php', icon: FileCode, category: 'XML' },
    { key: 'xml-to-png', name: 'XML to PNG', description: 'Convert XML to PNG (Image).', href: '/tools/xml-to-png', icon: FileCode, category: 'XML' },
    { key: 'xml-to-protobuf', name: 'XML to Protobuf', description: 'Convert XML to Protobuf.', href: '/tools/xml-to-protobuf', icon: FileCode, category: 'XML' },
    { key: 'xml-to-qlik', name: 'XML to Qlik', description: 'Convert XML to Qlik.', href: '/tools/xml-to-qlik', icon: FileCode, category: 'XML' },
    { key: 'xml-to-rdataframe', name: 'XML to R DataFrame', description: 'Convert XML to R DataFrame.', href: '/tools/xml-to-rdataframe', icon: FileCode, category: 'XML' },
    { key: 'xml-to-rdf', name: 'XML to RDF', description: 'Convert XML to RDF.', href: '/tools/xml-to-rdf', icon: FileCode, category: 'XML' },
    { key: 'xml-to-restructuredtext', name: 'XML to reStructuredText', description: 'Convert XML to reStructuredText.', href: '/tools/xml-to-restructuredtext', icon: FileCode, category: 'XML' },
    { key: 'xml-to-ruby', name: 'XML to Ruby', description: 'Convert XML to Ruby.', href: '/tools/xml-to-ruby', icon: FileCode, category: 'XML' },
    { key: 'xml-to-sql', name: 'XML to SQL', description: 'Convert XML to SQL.', href: '/tools/xml-to-sql', icon: FileCode, category: 'XML' },
    { key: 'xml-to-textile', name: 'XML to Textile', description: 'Convert XML to Textile.', href: '/tools/xml-to-textile', icon: FileCode, category: 'XML' },
    { key: 'xml-to-toml', name: 'XML to TOML', description: 'Convert XML to TOML.', href: '/tools/xml-to-toml', icon: FileCode, category: 'XML' },
    { key: 'xml-to-tracwiki', name: 'XML to TracWiki', description: 'Convert XML to TracWiki.', href: '/tools/xml-to-tracwiki', icon: FileCode, category: 'XML' },
    { key: 'xml-to-xml', name: 'XML to XML', description: 'Format/Beautify XML.', href: '/tools/xml-to-xml', icon: FileCode, category: 'XML' },
    { key: 'xml-to-yaml', name: 'XML to YAML', description: 'Convert XML to YAML.', href: '/tools/xml-to-yaml', icon: FileCode, category: 'XML' },

    // MySQL Converters (Reusing Database Icon, slightly different category name technically but functionally similar to SQL. User asked for specific "MySQL" and "MediaWiki")
    { key: 'mysql-to-actionscript', name: 'MySQL to ActionScript', description: 'Convert MySQL to ActionScript.', href: '/tools/mysql-to-actionscript', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-ascii', name: 'MySQL to ASCII', description: 'Convert MySQL to ASCII.', href: '/tools/mysql-to-ascii', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-asciidoc', name: 'MySQL to AsciiDoc', description: 'Convert MySQL to AsciiDoc.', href: '/tools/mysql-to-asciidoc', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-asp', name: 'MySQL to ASP', description: 'Convert MySQL to ASP.', href: '/tools/mysql-to-asp', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-avro', name: 'MySQL to Avro', description: 'Convert MySQL to Avro.', href: '/tools/mysql-to-avro', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-bbcode', name: 'MySQL to BBCode', description: 'Convert MySQL to BBCode.', href: '/tools/mysql-to-bbcode', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-csv', name: 'MySQL to CSV', description: 'Convert MySQL to CSV.', href: '/tools/mysql-to-csv', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-dax', name: 'MySQL to DAX', description: 'Convert MySQL to DAX.', href: '/tools/mysql-to-dax', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-excel', name: 'MySQL to Excel', description: 'Convert MySQL to Excel.', href: '/tools/mysql-to-excel', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-firebase', name: 'MySQL to Firebase', description: 'Convert MySQL to Firebase.', href: '/tools/mysql-to-firebase', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-html', name: 'MySQL to HTML', description: 'Convert MySQL to HTML.', href: '/tools/mysql-to-html', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-ini', name: 'MySQL to INI', description: 'Convert MySQL to INI.', href: '/tools/mysql-to-ini', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-jira', name: 'MySQL to Jira', description: 'Convert MySQL to Jira.', href: '/tools/mysql-to-jira', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-jpeg', name: 'MySQL to JPEG', description: 'Convert MySQL to JPEG (Image).', href: '/tools/mysql-to-jpeg', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-json', name: 'MySQL to JSON', description: 'Convert MySQL to JSON.', href: '/tools/mysql-to-json', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-jsonlines', name: 'MySQL to JSON Lines', description: 'Convert MySQL to JSON Lines.', href: '/tools/mysql-to-jsonlines', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-latex', name: 'MySQL to LaTeX', description: 'Convert MySQL to LaTeX.', href: '/tools/mysql-to-latex', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-magic', name: 'MySQL to Magic', description: 'Convert MySQL to Magic.', href: '/tools/mysql-to-magic', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-markdown', name: 'MySQL to Markdown', description: 'Convert MySQL to Markdown.', href: '/tools/mysql-to-markdown', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-matlab', name: 'MySQL to MATLAB', description: 'Convert MySQL to MATLAB.', href: '/tools/mysql-to-matlab', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-mediawiki', name: 'MySQL to MediaWiki', description: 'Convert MySQL to MediaWiki.', href: '/tools/mysql-to-mediawiki', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-pandasdataframe', name: 'MySQL to Pandas', description: 'Convert MySQL to Pandas.', href: '/tools/mysql-to-pandasdataframe', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-pdf', name: 'MySQL to PDF', description: 'Convert MySQL to PDF.', href: '/tools/mysql-to-pdf', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-php', name: 'MySQL to PHP', description: 'Convert MySQL to PHP.', href: '/tools/mysql-to-php', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-png', name: 'MySQL to PNG', description: 'Convert MySQL to PNG (Image).', href: '/tools/mysql-to-png', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-protobuf', name: 'MySQL to Protobuf', description: 'Convert MySQL to Protobuf.', href: '/tools/mysql-to-protobuf', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-qlik', name: 'MySQL to Qlik', description: 'Convert MySQL to Qlik.', href: '/tools/mysql-to-qlik', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-rdataframe', name: 'MySQL to R DataFrame', description: 'Convert MySQL to R DataFrame.', href: '/tools/mysql-to-rdataframe', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-rdf', name: 'MySQL to RDF', description: 'Convert MySQL to RDF.', href: '/tools/mysql-to-rdf', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-restructuredtext', name: 'MySQL to reStructuredText', description: 'Convert MySQL to reStructuredText.', href: '/tools/mysql-to-restructuredtext', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-ruby', name: 'MySQL to Ruby', description: 'Convert MySQL to Ruby.', href: '/tools/mysql-to-ruby', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-sql', name: 'MySQL to SQL', description: 'Format/Clean MySQL.', href: '/tools/mysql-to-sql', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-textile', name: 'MySQL to Textile', description: 'Convert MySQL to Textile.', href: '/tools/mysql-to-textile', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-toml', name: 'MySQL to TOML', description: 'Convert MySQL to TOML.', href: '/tools/mysql-to-toml', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-tracwiki', name: 'MySQL to TracWiki', description: 'Convert MySQL to TracWiki.', href: '/tools/mysql-to-tracwiki', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-xml', name: 'MySQL to XML', description: 'Convert MySQL to XML.', href: '/tools/mysql-to-xml', icon: Database, category: 'MySQL' },
    { key: 'mysql-to-yaml', name: 'MySQL to YAML', description: 'Convert MySQL to YAML.', href: '/tools/mysql-to-yaml', icon: Database, category: 'MySQL' },

    // MediaWiki Converters
    { key: 'mediawiki-to-actionscript', name: 'MediaWiki to ActionScript', description: 'Convert MediaWiki to ActionScript.', href: '/tools/mediawiki-to-actionscript', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-ascii', name: 'MediaWiki to ASCII', description: 'Convert MediaWiki to ASCII.', href: '/tools/mediawiki-to-ascii', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-asciidoc', name: 'MediaWiki to AsciiDoc', description: 'Convert MediaWiki to AsciiDoc.', href: '/tools/mediawiki-to-asciidoc', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-asp', name: 'MediaWiki to ASP', description: 'Convert MediaWiki to ASP.', href: '/tools/mediawiki-to-asp', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-avro', name: 'MediaWiki to Avro', description: 'Convert MediaWiki to Avro.', href: '/tools/mediawiki-to-avro', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-bbcode', name: 'MediaWiki to BBCode', description: 'Convert MediaWiki to BBCode.', href: '/tools/mediawiki-to-bbcode', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-csv', name: 'MediaWiki to CSV', description: 'Convert MediaWiki to CSV.', href: '/tools/mediawiki-to-csv', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-dax', name: 'MediaWiki to DAX', description: 'Convert MediaWiki to DAX.', href: '/tools/mediawiki-to-dax', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-excel', name: 'MediaWiki to Excel', description: 'Convert MediaWiki to Excel.', href: '/tools/mediawiki-to-excel', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-firebase', name: 'MediaWiki to Firebase', description: 'Convert MediaWiki to Firebase.', href: '/tools/mediawiki-to-firebase', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-html', name: 'MediaWiki to HTML', description: 'Convert MediaWiki to HTML.', href: '/tools/mediawiki-to-html', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-ini', name: 'MediaWiki to INI', description: 'Convert MediaWiki to INI.', href: '/tools/mediawiki-to-ini', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-jira', name: 'MediaWiki to Jira', description: 'Convert MediaWiki to Jira.', href: '/tools/mediawiki-to-jira', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-jpeg', name: 'MediaWiki to JPEG', description: 'Convert MediaWiki to JPEG (Image).', href: '/tools/mediawiki-to-jpeg', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-json', name: 'MediaWiki to JSON', description: 'Convert MediaWiki to JSON.', href: '/tools/mediawiki-to-json', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-jsonlines', name: 'MediaWiki to JSON Lines', description: 'Convert MediaWiki to JSON Lines.', href: '/tools/mediawiki-to-jsonlines', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-latex', name: 'MediaWiki to LaTeX', description: 'Convert MediaWiki to LaTeX.', href: '/tools/mediawiki-to-latex', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-magic', name: 'MediaWiki to Magic', description: 'Convert MediaWiki to Magic.', href: '/tools/mediawiki-to-magic', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-markdown', name: 'MediaWiki to Markdown', description: 'Convert MediaWiki to Markdown.', href: '/tools/mediawiki-to-markdown', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-matlab', name: 'MediaWiki to MATLAB', description: 'Convert MediaWiki to MATLAB.', href: '/tools/mediawiki-to-matlab', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-mediawiki', name: 'MediaWiki to MediaWiki', description: 'Format/Beautify MediaWiki.', href: '/tools/mediawiki-to-mediawiki', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-pandasdataframe', name: 'MediaWiki to Pandas', description: 'Convert MediaWiki to Pandas.', href: '/tools/mediawiki-to-pandasdataframe', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-pdf', name: 'MediaWiki to PDF', description: 'Convert MediaWiki to PDF.', href: '/tools/mediawiki-to-pdf', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-php', name: 'MediaWiki to PHP', description: 'Convert MediaWiki to PHP.', href: '/tools/mediawiki-to-php', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-png', name: 'MediaWiki to PNG', description: 'Convert MediaWiki to PNG (Image).', href: '/tools/mediawiki-to-png', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-protobuf', name: 'MediaWiki to Protobuf', description: 'Convert MediaWiki to Protobuf.', href: '/tools/mediawiki-to-protobuf', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-qlik', name: 'MediaWiki to Qlik', description: 'Convert MediaWiki to Qlik.', href: '/tools/mediawiki-to-qlik', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-rdataframe', name: 'MediaWiki to R DataFrame', description: 'Convert MediaWiki to R DataFrame.', href: '/tools/mediawiki-to-rdataframe', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-rdf', name: 'MediaWiki to RDF', description: 'Convert MediaWiki to RDF.', href: '/tools/mediawiki-to-rdf', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-restructuredtext', name: 'MediaWiki to reStructuredText', description: 'Convert MediaWiki to reStructuredText.', href: '/tools/mediawiki-to-restructuredtext', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-ruby', name: 'MediaWiki to Ruby', description: 'Convert MediaWiki to Ruby.', href: '/tools/mediawiki-to-ruby', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-sql', name: 'MediaWiki to SQL', description: 'Convert MediaWiki to SQL.', href: '/tools/mediawiki-to-sql', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-textile', name: 'MediaWiki to Textile', description: 'Convert MediaWiki to Textile.', href: '/tools/mediawiki-to-textile', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-toml', name: 'MediaWiki to TOML', description: 'Convert MediaWiki to TOML.', href: '/tools/mediawiki-to-toml', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-tracwiki', name: 'MediaWiki to TracWiki', description: 'Convert MediaWiki to TracWiki.', href: '/tools/mediawiki-to-tracwiki', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-xml', name: 'MediaWiki to XML', description: 'Convert MediaWiki to XML.', href: '/tools/mediawiki-to-xml', icon: FileCode, category: 'MediaWiki' },
    { key: 'mediawiki-to-yaml', name: 'MediaWiki to YAML', description: 'Convert MediaWiki to YAML.', href: '/tools/mediawiki-to-yaml', icon: FileCode, category: 'MediaWiki' },
]

export const categories: { key: ModuleCategory; name: string }[] = [
    { key: 'General', name: 'Tổng quan' },
    { key: 'Network', name: 'Mạng & Network' },
    { key: 'Utilities', name: 'Tiện ích' },
    { key: 'Table', name: 'Table Converter' },
    { key: 'JSON', name: 'JSON Converter' },
    { key: 'CSV', name: 'CSV Converter' },
    { key: 'Markdown', name: 'Markdown Converter' },
    { key: 'HTML', name: 'HTML Converter' },
    { key: 'SQL', name: 'SQL Converter' },
    { key: 'LaTeX', name: 'LaTeX Converter' },
    { key: 'XML', name: 'XML Converter' },
    { key: 'MySQL', name: 'MySQL Converter' },
    { key: 'MediaWiki', name: 'MediaWiki Converter' },
    { key: 'PDF', name: 'PDF Tools' },
]

