-- Migration 012: Tool file storage and module catalog hardening
-- Final files generated by server-side tasks are stored in Supabase Storage,
-- not in the Vercel filesystem.

ALTER TABLE modules ADD COLUMN IF NOT EXISTS href text;
ALTER TABLE modules ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE modules ADD COLUMN IF NOT EXISTS is_new boolean DEFAULT false;
ALTER TABLE modules ADD COLUMN IF NOT EXISTS is_popular boolean DEFAULT false;

CREATE INDEX IF NOT EXISTS idx_modules_enabled_category
  ON modules (is_enabled, category, sort_order);

CREATE TABLE IF NOT EXISTS tool_files (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  module_key text REFERENCES modules(key) ON DELETE SET NULL,
  bucket text NOT NULL DEFAULT 'tool-files',
  storage_path text NOT NULL UNIQUE,
  original_name text NOT NULL,
  result_name text,
  mime_type text,
  size_bytes bigint,
  kind text NOT NULL DEFAULT 'output' CHECK (kind IN ('input', 'output', 'temp')),
  expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE tool_files ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own tool files" ON tool_files;
DROP POLICY IF EXISTS "Users can delete own tool files" ON tool_files;

CREATE POLICY "Users can view own tool files"
  ON tool_files FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "Users can delete own tool files"
  ON tool_files FOR DELETE
  USING (user_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_tool_files_user_created
  ON tool_files (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_tool_files_expires
  ON tool_files (expires_at)
  WHERE expires_at IS NOT NULL;

INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES ('tool-files', 'tool-files', false, 524288000)
ON CONFLICT (id) DO UPDATE
SET public = false,
    file_size_limit = 524288000;

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  default_role_id uuid;
BEGIN
  SELECT id INTO default_role_id
  FROM roles
  WHERE name = 'User'
  LIMIT 1;

  INSERT INTO user_profiles (id, full_name, role_id, is_active)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
    default_role_id,
    true
  )
  ON CONFLICT (id) DO NOTHING;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();
