-- Migration 013: Seed the full module catalog from config/modules.ts
-- Keeps SQL data aligned with the application catalog. Existing admin on/off
-- choices are preserved because is_enabled is only used for newly inserted rows.

INSERT INTO modules (
  key,
  name,
  description,
  icon,
  is_enabled,
  sort_order,
  href,
  category,
  is_new,
  is_popular
) VALUES
  ('dns-lookup', 'DNS Lookup', 'Tra cứu thông tin DNS (A, MX, NS, TXT...) của tên miền nhanh chóng.', 'dns-lookup', true, 1, '/tools/dns-lookup', 'Network', true, true),
  ('ip-lookup', 'IP Lookup', 'Tra cứu thông tin địa chỉ IP (ISP, Vị trí, ASN) chi tiết.', 'ip-lookup', true, 2, '/tools/ip-lookup', 'Network', true, true),
  ('ssl-lookup', 'SSL Lookup', 'Kiểm tra thông tin chứng chỉ SSL/TLS và thời hạn sử dụng.', 'ssl-lookup', true, 3, '/tools/ssl-lookup', 'Utilities', true, false),
  ('whois-lookup', 'Whois Lookup', 'Kiểm tra thông tin tên miền, ngày đăng ký và nhà cung cấp.', 'whois-lookup', true, 4, '/tools/whois-lookup', 'Utilities', true, false),
  ('ping-tool', 'Ping & Port', 'Kiểm tra trạng thái Website (HTTP Ping) và Open Port.', 'ping-tool', true, 5, '/tools/ping', 'Network', true, false),
  ('md5-generator', 'MD5 Generator', 'Công cụ tạo mã MD5 Hash nhanh chóng.', 'md5-generator', true, 6, '/tools/md5-generator', 'Utilities', true, false),
  ('base64-converter', 'Base64 Converter', 'Mã hóa và giải mã Base64 (Encode/Decode).', 'base64-converter', true, 7, '/tools/base64-converter', 'Utilities', true, false),
  ('uuid-generator', 'UUID Generator', 'Tạo mã UUID v4 ngẫu nhiên (Bulk supported).', 'uuid-generator', true, 8, '/tools/uuid-generator', 'Utilities', true, false),
  ('bcrypt-generator', 'Bcrypt Generator', 'Tạo mã băm Bcrypt và kiểm tra mật khẩu.', 'bcrypt-generator', true, 9, '/tools/bcrypt-generator', 'Utilities', true, false),
  ('spin-wheel', 'Spin Wheel', 'Công cụ quay số ngẫu nhiên để chọn một mục từ danh sách.', 'spin-wheel', true, 10, '/tools/spin-wheel', 'Utilities', true, true),
  ('video-downloader', 'Video Downloader', 'Tải video chất lượng cao từ YouTube.', 'video-downloader', true, 11, '/tools/video-downloader', 'Utilities', true, true),
  ('scribd-downloader', 'Scribd Downloader', 'Tải tài liệu PDF từ Scribd mà không cần tài khoản.', 'scribd-downloader', true, 12, '/tools/scribd-downloader', 'Utilities', true, true),
  ('password-generator', 'Password Generator', 'Tạo mật khẩu mạnh ngẫu nhiên (Strong Password).', 'password-generator', true, 13, '/tools/password-generator', 'Utilities', true, false),
  ('slug-generator', 'Slug Generator', 'Tạo URL Slug thân thiện SEO từ văn bản.', 'slug-generator', true, 14, '/tools/slug-generator', 'Utilities', true, false),
  ('html-minifier', 'HTML Minifier', 'Tối ưu hóa và nén mã HTML (remove whitespace/comments).', 'html-minifier', true, 15, '/tools/html-minifier', 'Utilities', true, false),
  ('css-minifier', 'CSS Minifier', 'Nén mã CSS/StyleSheet để tối ưu tốc độ tải trang.', 'css-minifier', true, 16, '/tools/css-minifier', 'Utilities', true, false),
  ('js-minifier', 'JS Minifier', 'Nén và tối ưu mã JavaScript (Basic Minification).', 'js-minifier', true, 17, '/tools/js-minifier', 'Utilities', true, false),
  ('user-agent-parser', 'User Agent Parser', 'Phân tích chuỗi User Agent để lấy thông tin thiết bị, OS, Browser.', 'user-agent-parser', true, 18, '/tools/user-agent-parser', 'Utilities', true, false),
  ('hosting-checker', 'Hosting Checker', 'Kiểm tra nhà cung cấp Hosting (ISP) và vị trí máy chủ của website.', 'hosting-checker', true, 19, '/tools/hosting-checker', 'Network', true, false),
  ('character-counter', 'Character Counter', 'Đếm số ký tự, từ, câu, đoạn văn trong văn bản.', 'character-counter', true, 20, '/tools/character-counter', 'Utilities', true, false),
  ('url-parser', 'URL Parser', 'Phân tích URL thành các thành phần: Protocol, Host, Path, Query Params...', 'url-parser', true, 21, '/tools/url-parser', 'Utilities', true, false),
  ('color-converter', 'Color Converter', 'Chuyển đổi mã màu giữa các định dạng Hex, RGB, HSL, CMYK.', 'color-converter', true, 22, '/tools/color-converter', 'Utilities', true, false),
  ('http-header-lookup', 'HTTP Header Lookup', 'Kiểm tra HTTP Response Headers và Status Code.', 'http-header-lookup', true, 23, '/tools/http-header-lookup', 'Network', true, false),
  ('duplicate-lines-remover', 'Duplicate Lines Remover', 'Lọc và xóa các dòng trùng lặp trong danh sách.', 'duplicate-lines-remover', true, 24, '/tools/duplicate-lines-remover', 'Utilities', true, false),
  ('idn-punycode-converter', 'IDN Punycode Converter', 'Chuyển đổi tên miền quốc tế (IDN) sang Punycode và ngược lại.', 'idn-punycode-converter', true, 25, '/tools/idn-punycode-converter', 'Utilities', true, false),
  ('json-validator', 'JSON Validator', 'Kiểm tra, định dạng (Beautify) và nén (Minify) mã JSON.', 'json-validator', true, 26, '/tools/json-validator', 'Utilities', true, false),
  ('meta-tag-checker', 'Meta Tag Checker', 'Phân tích thẻ Meta, SEO và Social Media.', 'meta-tag-checker', true, 27, '/tools/meta-tag-checker', 'Network', true, false),
  ('sql-formatter', 'SQL Formatter', 'Định dạng và làm đẹp câu lệnh SQL (Beautify).', 'sql-formatter', true, 28, '/tools/sql-formatter', 'Utilities', true, false),
  ('html-entity-converter', 'HTML Entity Converter', 'Chuyển đổi ký tự đặc biệt sang HTML Entities.', 'html-entity-converter', true, 29, '/tools/html-entity-converter', 'Utilities', true, false),
  ('binary-converter', 'Binary Converter', 'Chuyển đổi văn bản sang nhị phân (010101).', 'binary-converter', true, 30, '/tools/binary-converter', 'Utilities', true, false),
  ('text-separator', 'Text Separator', 'Tách hoặc gộp danh sách văn bản theo ký tự.', 'text-separator', true, 31, '/tools/text-separator', 'Utilities', true, false),
  ('hex-converter', 'Hex Converter', 'Chuyển đổi Hex, Decimal và Text.', 'hex-converter', true, 32, '/tools/hex-converter', 'Utilities', true, false),
  ('signature-generator', 'Signature Generator', 'Tạo chữ ký điện tử (Digital Signature) online.', 'signature-generator', true, 33, '/tools/signature-generator', 'Utilities', true, false),
  ('lorem-ipsum-generator', 'Lorem Ipsum Generator', 'Tạo văn bản giả (Dummy Text) Lorem Ipsum.', 'lorem-ipsum-generator', true, 34, '/tools/lorem-ipsum-generator', 'Utilities', true, false),
  ('temperature-converter', 'Temperature Converter', 'Chuyển đổi nhiệt độ (Celsius, Fahrenheit, Kelvin).', 'temperature-converter', true, 35, '/tools/temperature-converter', 'Utilities', true, false),
  ('speed-converter', 'Speed Converter', 'Chuyển đổi vận tốc (MPH <-> KPH).', 'speed-converter', true, 36, '/tools/speed-converter', 'Utilities', true, false),
  ('roman-numeral-converter', 'Roman Numeral Converter', 'Chuyển đổi số La Mã (Roman Numerals) và số tự nhiên.', 'roman-numeral-converter', true, 37, '/tools/roman-numeral-converter', 'Utilities', true, false),
  ('data-converter', 'Data Unit Converter', 'Chuyển đổi đơn vị dữ liệu (Bits, Bytes, KB, MB, GB, TB, KiB, MiB...).', 'data-converter', true, 38, '/tools/data-converter', 'Utilities', true, false),
  ('shortlinks', 'Shortlinks', 'Tạo và quản lý URL rút gọn với mật khẩu bảo vệ và thời gian hết hạn.', 'shortlinks', true, 39, '/dashboard/shortlinks', 'Utilities', true, true),
  ('mail-system', 'Mail System', 'Gửi email qua SMTP, quản lý tài khoản và theo dõi lịch sử gửi mail.', 'mail-system', true, 40, '/dashboard/mail', 'Utilities', true, true),
  ('quiz-system', 'Quiz System', 'Tạo, quản lý và chia sẻ các bài trắc nghiệm kiến thức.', 'quiz-system', true, 41, '/dashboard/quiz', 'Utilities', true, true),
  ('merge-pdf', 'Merge PDF', 'Ghép nhiều file PDF thành một file duy nhất.', 'merge-pdf', true, 42, '/tools/merge-pdf', 'PDF', true, true),
  ('split-pdf', 'Split PDF', 'Chia nhỏ file PDF hoặc trích xuất các trang cụ thể.', 'split-pdf', true, 43, '/tools/split-pdf', 'PDF', true, true),
  ('pdf-to-image', 'PDF to Image', 'Chuyển đổi các trang PDF thành hình ảnh (PNG).', 'pdf-to-image', true, 44, '/tools/pdf-to-image', 'PDF', true, true),
  ('image-to-pdf', 'Image to PDF', 'Chuyển đổi hình ảnh (PNG, JPG) thành file PDF.', 'image-to-pdf', true, 45, '/tools/image-to-pdf', 'PDF', true, true),
  ('rotate-pdf', 'Rotate PDF', 'Xoay các trang trong file PDF (Trái, Phải, 180 độ).', 'rotate-pdf', true, 46, '/tools/rotate-pdf', 'PDF', true, true),
  ('protect-pdf', 'Protect PDF', 'Đặt mật khẩu bảo vệ file PDF.', 'protect-pdf', true, 47, '/tools/protect-pdf', 'PDF', true, true),
  ('unlock-pdf', 'Unlock PDF', 'Gỡ bỏ mật khẩu khỏi file PDF.', 'unlock-pdf', true, 48, '/tools/unlock-pdf', 'PDF', true, true),
  ('webp-to-png', 'WEBP to PNG', 'Chuyển đổi ảnh WEBP sang PNG.', 'webp-to-png', true, 49, '/tools/webp-to-png', 'Image', true, true),
  ('jfif-to-png', 'JFIF to PNG', 'Chuyển đổi JFIF sang PNG.', 'jfif-to-png', true, 50, '/tools/jfif-to-png', 'Image', true, true),
  ('png-to-svg', 'PNG to SVG', 'Chuyển đổi PNG sang SVG (Vector hóa).', 'png-to-svg', true, 51, '/tools/png-to-svg', 'Image', true, true),
  ('heic-to-jpg', 'HEIC to JPG', 'Chuyển đổi HEIC sang JPG (cho iPhone/iPad).', 'heic-to-jpg', true, 52, '/tools/heic-to-jpg', 'Image', true, true),
  ('heic-to-png', 'HEIC to PNG', 'Chuyển đổi HEIC sang PNG.', 'heic-to-png', true, 53, '/tools/heic-to-png', 'Image', true, true),
  ('webp-to-jpg', 'WEBP to JPG', 'Chuyển đổi WEBP sang JPG.', 'webp-to-jpg', true, 54, '/tools/webp-to-jpg', 'Image', true, true),
  ('svg-converter', 'SVG to Image', 'Chuyển đổi file SVG sang PNG hoặc JPG.', 'svg-converter', true, 55, '/tools/svg-converter', 'Image', true, true),
  ('image-converter', 'Universal Image Converter', 'Chuyển đổi đa năng cho hơn 80 định dạng ảnh (PNG, JPG, WEBP, HEIC, RAW...).', 'image-converter', true, 56, '/tools/image-converter', 'Image', true, true),
  ('audio-converter', 'Universal Audio Converter', 'Chuyển đổi đa năng cho hơn 60 định dạng âm thanh (MP3, WAV, FLAC, OGG, AAC...).', 'audio-converter', true, 57, '/tools/audio-converter', 'Audio', true, true),
  ('font-converter', 'Universal Font Converter', 'Chuyển đổi đa năng các định dạng Font (TTF, OTF, WOFF...).', 'font-converter', true, 58, '/tools/font-converter', 'Font', true, false),
  ('video-converter', 'Universal Video Converter', 'Chuyển đổi đa năng cho hơn 30 định dạng video (MP4, AVI, MKV, MOV, WEBM...).', 'video-converter', true, 59, '/tools/video-converter', 'Video', true, true),
  ('excel-to-actionscript', 'Excel to ActionScript', 'Convert Excel to ActionScript.', 'excel-to-actionscript', true, 60, '/tools/excel-to-actionscript', 'Table', false, false),
  ('excel-to-ascii', 'Excel to ASCII', 'Convert Excel to ASCII Table.', 'excel-to-ascii', true, 61, '/tools/excel-to-ascii', 'Table', false, false),
  ('excel-to-asciidoc', 'Excel to AsciiDoc', 'Convert Excel to AsciiDoc.', 'excel-to-asciidoc', true, 62, '/tools/excel-to-asciidoc', 'Table', false, false),
  ('excel-to-asp', 'Excel to ASP', 'Convert Excel to ASP.', 'excel-to-asp', true, 63, '/tools/excel-to-asp', 'Table', false, false),
  ('excel-to-avro', 'Excel to Avro', 'Convert Excel to Avro.', 'excel-to-avro', true, 64, '/tools/excel-to-avro', 'Table', false, false),
  ('excel-to-bbcode', 'Excel to BBCode', 'Convert Excel to BBCode.', 'excel-to-bbcode', true, 65, '/tools/excel-to-bbcode', 'Table', false, false),
  ('excel-to-csv', 'Excel to CSV', 'Convert Excel to CSV.', 'excel-to-csv', true, 66, '/tools/excel-to-csv', 'Table', false, false),
  ('excel-to-dax', 'Excel to DAX', 'Convert Excel to DAX.', 'excel-to-dax', true, 67, '/tools/excel-to-dax', 'Table', false, false),
  ('excel-to-excel', 'Excel to Excel', 'Check/Validate Excel format.', 'excel-to-excel', true, 68, '/tools/excel-to-excel', 'Table', false, false),
  ('excel-to-firebase', 'Excel to Firebase', 'Convert Excel to Firebase JSON.', 'excel-to-firebase', true, 69, '/tools/excel-to-firebase', 'Table', false, false),
  ('excel-to-html', 'Excel to HTML', 'Convert Excel to HTML Table.', 'excel-to-html', true, 70, '/tools/excel-to-html', 'Table', false, false),
  ('excel-to-ini', 'Excel to INI', 'Convert Excel to INI.', 'excel-to-ini', true, 71, '/tools/excel-to-ini', 'Table', false, false),
  ('excel-to-jira', 'Excel to Jira', 'Convert Excel to Jira markup.', 'excel-to-jira', true, 72, '/tools/excel-to-jira', 'Table', false, false),
  ('excel-to-jpeg', 'Excel to JPEG', 'Convert Excel sheet to JPEG image.', 'excel-to-jpeg', true, 73, '/tools/excel-to-jpeg', 'Table', false, false),
  ('excel-to-json', 'Excel to JSON', 'Convert Excel to JSON.', 'excel-to-json', true, 74, '/tools/excel-to-json', 'Table', false, false),
  ('excel-to-jsonlines', 'Excel to JSON Lines', 'Convert Excel to JSON Lines.', 'excel-to-jsonlines', true, 75, '/tools/excel-to-jsonlines', 'Table', false, false),
  ('excel-to-latex', 'Excel to LaTeX', 'Convert Excel to LaTeX.', 'excel-to-latex', true, 76, '/tools/excel-to-latex', 'Table', false, false),
  ('excel-to-magic', 'Excel to Magic', 'Convert Excel to Magic.', 'excel-to-magic', true, 77, '/tools/excel-to-magic', 'Table', false, false),
  ('excel-to-markdown', 'Excel to Markdown', 'Convert Excel to Markdown Table.', 'excel-to-markdown', true, 78, '/tools/excel-to-markdown', 'Table', false, false),
  ('excel-to-matlab', 'Excel to MATLAB', 'Convert Excel to MATLAB.', 'excel-to-matlab', true, 79, '/tools/excel-to-matlab', 'Table', false, false),
  ('excel-to-mediawiki', 'Excel to MediaWiki', 'Convert Excel to MediaWiki Table.', 'excel-to-mediawiki', true, 80, '/tools/excel-to-mediawiki', 'Table', false, false),
  ('excel-to-pandasdataframe', 'Excel to Pandas', 'Convert Excel to Pandas DataFrame code.', 'excel-to-pandasdataframe', true, 81, '/tools/excel-to-pandasdataframe', 'Table', false, false),
  ('excel-to-pdf', 'Excel to PDF', 'Convert Excel to PDF.', 'excel-to-pdf', true, 82, '/tools/excel-to-pdf', 'Table', false, false),
  ('excel-to-php', 'Excel to PHP', 'Convert Excel to PHP Array.', 'excel-to-php', true, 83, '/tools/excel-to-php', 'Table', false, false),
  ('excel-to-png', 'Excel to PNG', 'Convert Excel sheet to PNG image.', 'excel-to-png', true, 84, '/tools/excel-to-png', 'Table', false, false),
  ('excel-to-protobuf', 'Excel to Protobuf', 'Convert Excel to Protobuf.', 'excel-to-protobuf', true, 85, '/tools/excel-to-protobuf', 'Table', false, false),
  ('excel-to-qlik', 'Excel to Qlik', 'Convert Excel to Qlik.', 'excel-to-qlik', true, 86, '/tools/excel-to-qlik', 'Table', false, false),
  ('excel-to-rdataframe', 'Excel to R DataFrame', 'Convert Excel to R DataFrame.', 'excel-to-rdataframe', true, 87, '/tools/excel-to-rdataframe', 'Table', false, false),
  ('excel-to-rdf', 'Excel to RDF', 'Convert Excel to RDF.', 'excel-to-rdf', true, 88, '/tools/excel-to-rdf', 'Table', false, false),
  ('excel-to-restructuredtext', 'Excel to reStructuredText', 'Convert Excel to reStructuredText.', 'excel-to-restructuredtext', true, 89, '/tools/excel-to-restructuredtext', 'Table', false, false),
  ('excel-to-ruby', 'Excel to Ruby', 'Convert Excel to Ruby Array.', 'excel-to-ruby', true, 90, '/tools/excel-to-ruby', 'Table', false, false),
  ('excel-to-sql', 'Excel to SQL', 'Convert Excel to SQL Insert Queries.', 'excel-to-sql', true, 91, '/tools/excel-to-sql', 'Table', false, false),
  ('excel-to-textile', 'Excel to Textile', 'Convert Excel to Textile.', 'excel-to-textile', true, 92, '/tools/excel-to-textile', 'Table', false, false),
  ('excel-to-toml', 'Excel to TOML', 'Convert Excel to TOML.', 'excel-to-toml', true, 93, '/tools/excel-to-toml', 'Table', false, false),
  ('excel-to-tracwiki', 'Excel to TracWiki', 'Convert Excel to TracWiki.', 'excel-to-tracwiki', true, 94, '/tools/excel-to-tracwiki', 'Table', false, false),
  ('excel-to-xml', 'Excel to XML', 'Convert Excel to XML.', 'excel-to-xml', true, 95, '/tools/excel-to-xml', 'Table', false, false),
  ('excel-to-yaml', 'Excel to YAML', 'Convert Excel to YAML.', 'excel-to-yaml', true, 96, '/tools/excel-to-yaml', 'Table', false, false),
  ('json-to-actionscript', 'JSON to ActionScript', 'Convert JSON to ActionScript.', 'json-to-actionscript', true, 97, '/tools/json-to-actionscript', 'JSON', false, false),
  ('json-to-ascii', 'JSON to ASCII', 'Convert JSON to ASCII Table.', 'json-to-ascii', true, 98, '/tools/json-to-ascii', 'JSON', false, false),
  ('json-to-asciidoc', 'JSON to AsciiDoc', 'Convert JSON to AsciiDoc.', 'json-to-asciidoc', true, 99, '/tools/json-to-asciidoc', 'JSON', false, false),
  ('json-to-asp', 'JSON to ASP', 'Convert JSON to ASP.', 'json-to-asp', true, 100, '/tools/json-to-asp', 'JSON', false, false),
  ('json-to-avro', 'JSON to Avro', 'Convert JSON to Avro.', 'json-to-avro', true, 101, '/tools/json-to-avro', 'JSON', false, false),
  ('json-to-bbcode', 'JSON to BBCode', 'Convert JSON to BBCode.', 'json-to-bbcode', true, 102, '/tools/json-to-bbcode', 'JSON', false, false),
  ('json-to-csv', 'JSON to CSV', 'Convert JSON to CSV.', 'json-to-csv', true, 103, '/tools/json-to-csv', 'JSON', false, false),
  ('json-to-dax', 'JSON to DAX', 'Convert JSON to DAX.', 'json-to-dax', true, 104, '/tools/json-to-dax', 'JSON', false, false),
  ('json-to-excel', 'JSON to Excel', 'Convert JSON to Excel.', 'json-to-excel', true, 105, '/tools/json-to-excel', 'JSON', false, false),
  ('json-to-firebase', 'JSON to Firebase', 'Convert JSON to Firebase.', 'json-to-firebase', true, 106, '/tools/json-to-firebase', 'JSON', false, false),
  ('json-to-html', 'JSON to HTML', 'Convert JSON to HTML Table.', 'json-to-html', true, 107, '/tools/json-to-html', 'JSON', false, false),
  ('json-to-ini', 'JSON to INI', 'Convert JSON to INI.', 'json-to-ini', true, 108, '/tools/json-to-ini', 'JSON', false, false),
  ('json-to-jira', 'JSON to Jira', 'Convert JSON to Jira markup.', 'json-to-jira', true, 109, '/tools/json-to-jira', 'JSON', false, false),
  ('json-to-jpeg', 'JSON to JPEG', 'Convert JSON to JPEG image.', 'json-to-jpeg', true, 110, '/tools/json-to-jpeg', 'JSON', false, false),
  ('json-to-json', 'JSON to JSON', 'Validate and Format JSON.', 'json-to-json', true, 111, '/tools/json-to-json', 'JSON', false, false),
  ('json-to-jsonlines', 'JSON to JSON Lines', 'Convert JSON to JSON Lines.', 'json-to-jsonlines', true, 112, '/tools/json-to-jsonlines', 'JSON', false, false),
  ('json-to-latex', 'JSON to LaTeX', 'Convert JSON to LaTeX.', 'json-to-latex', true, 113, '/tools/json-to-latex', 'JSON', false, false),
  ('json-to-magic', 'JSON to Magic', 'Convert JSON to Magic.', 'json-to-magic', true, 114, '/tools/json-to-magic', 'JSON', false, false),
  ('json-to-markdown', 'JSON to Markdown', 'Convert JSON to Markdown Table.', 'json-to-markdown', true, 115, '/tools/json-to-markdown', 'JSON', false, false),
  ('json-to-matlab', 'JSON to MATLAB', 'Convert JSON to MATLAB.', 'json-to-matlab', true, 116, '/tools/json-to-matlab', 'JSON', false, false),
  ('json-to-mediawiki', 'JSON to MediaWiki', 'Convert JSON to MediaWiki Table.', 'json-to-mediawiki', true, 117, '/tools/json-to-mediawiki', 'JSON', false, false),
  ('json-to-pandasdataframe', 'JSON to Pandas', 'Convert JSON to Pandas DataFrame.', 'json-to-pandasdataframe', true, 118, '/tools/json-to-pandasdataframe', 'JSON', false, false),
  ('json-to-pdf', 'JSON to PDF', 'Convert JSON to PDF.', 'json-to-pdf', true, 119, '/tools/json-to-pdf', 'JSON', false, false),
  ('json-to-php', 'JSON to PHP', 'Convert JSON to PHP Array.', 'json-to-php', true, 120, '/tools/json-to-php', 'JSON', false, false),
  ('json-to-png', 'JSON to PNG', 'Convert JSON to PNG image.', 'json-to-png', true, 121, '/tools/json-to-png', 'JSON', false, false),
  ('json-to-protobuf', 'JSON to Protobuf', 'Convert JSON to Protobuf.', 'json-to-protobuf', true, 122, '/tools/json-to-protobuf', 'JSON', false, false),
  ('json-to-qlik', 'JSON to Qlik', 'Convert JSON to Qlik.', 'json-to-qlik', true, 123, '/tools/json-to-qlik', 'JSON', false, false),
  ('json-to-rdataframe', 'JSON to R DataFrame', 'Convert JSON to R DataFrame.', 'json-to-rdataframe', true, 124, '/tools/json-to-rdataframe', 'JSON', false, false),
  ('json-to-rdf', 'JSON to RDF', 'Convert JSON to RDF.', 'json-to-rdf', true, 125, '/tools/json-to-rdf', 'JSON', false, false),
  ('json-to-restructuredtext', 'JSON to reStructuredText', 'Convert JSON to reStructuredText.', 'json-to-restructuredtext', true, 126, '/tools/json-to-restructuredtext', 'JSON', false, false),
  ('json-to-ruby', 'JSON to Ruby', 'Convert JSON to Ruby.', 'json-to-ruby', true, 127, '/tools/json-to-ruby', 'JSON', false, false),
  ('json-to-sql', 'JSON to SQL', 'Convert JSON to SQL.', 'json-to-sql', true, 128, '/tools/json-to-sql', 'JSON', false, false),
  ('json-to-textile', 'JSON to Textile', 'Convert JSON to Textile.', 'json-to-textile', true, 129, '/tools/json-to-textile', 'JSON', false, false),
  ('json-to-toml', 'JSON to TOML', 'Convert JSON to TOML.', 'json-to-toml', true, 130, '/tools/json-to-toml', 'JSON', false, false),
  ('json-to-tracwiki', 'JSON to TracWiki', 'Convert JSON to TracWiki.', 'json-to-tracwiki', true, 131, '/tools/json-to-tracwiki', 'JSON', false, false),
  ('json-to-xml', 'JSON to XML', 'Convert JSON to XML.', 'json-to-xml', true, 132, '/tools/json-to-xml', 'JSON', false, false),
  ('json-to-yaml', 'JSON to YAML', 'Convert JSON to YAML.', 'json-to-yaml', true, 133, '/tools/json-to-yaml', 'JSON', false, false),
  ('csv-to-actionscript', 'CSV to ActionScript', 'Convert CSV to ActionScript.', 'csv-to-actionscript', true, 134, '/tools/csv-to-actionscript', 'CSV', false, false),
  ('csv-to-ascii', 'CSV to ASCII', 'Convert CSV to ASCII Table.', 'csv-to-ascii', true, 135, '/tools/csv-to-ascii', 'CSV', false, false),
  ('csv-to-asciidoc', 'CSV to AsciiDoc', 'Convert CSV to AsciiDoc.', 'csv-to-asciidoc', true, 136, '/tools/csv-to-asciidoc', 'CSV', false, false),
  ('csv-to-asp', 'CSV to ASP', 'Convert CSV to ASP.', 'csv-to-asp', true, 137, '/tools/csv-to-asp', 'CSV', false, false),
  ('csv-to-avro', 'CSV to Avro', 'Convert CSV to Avro.', 'csv-to-avro', true, 138, '/tools/csv-to-avro', 'CSV', false, false),
  ('csv-to-bbcode', 'CSV to BBCode', 'Convert CSV to BBCode.', 'csv-to-bbcode', true, 139, '/tools/csv-to-bbcode', 'CSV', false, false),
  ('csv-to-csv', 'CSV to CSV', 'Format and Clean CSV.', 'csv-to-csv', true, 140, '/tools/csv-to-csv', 'CSV', false, false),
  ('csv-to-dax', 'CSV to DAX', 'Convert CSV to DAX.', 'csv-to-dax', true, 141, '/tools/csv-to-dax', 'CSV', false, false),
  ('csv-to-excel', 'CSV to Excel', 'Convert CSV to Excel.', 'csv-to-excel', true, 142, '/tools/csv-to-excel', 'CSV', false, false),
  ('csv-to-firebase', 'CSV to Firebase', 'Convert CSV to Firebase.', 'csv-to-firebase', true, 143, '/tools/csv-to-firebase', 'CSV', false, false),
  ('csv-to-html', 'CSV to HTML', 'Convert CSV to HTML Table.', 'csv-to-html', true, 144, '/tools/csv-to-html', 'CSV', false, false),
  ('csv-to-ini', 'CSV to INI', 'Convert CSV to INI.', 'csv-to-ini', true, 145, '/tools/csv-to-ini', 'CSV', false, false),
  ('csv-to-jira', 'CSV to Jira', 'Convert CSV to Jira markup.', 'csv-to-jira', true, 146, '/tools/csv-to-jira', 'CSV', false, false),
  ('csv-to-jpeg', 'CSV to JPEG', 'Convert CSV to JPEG image.', 'csv-to-jpeg', true, 147, '/tools/csv-to-jpeg', 'CSV', false, false),
  ('csv-to-json', 'CSV to JSON', 'Convert CSV to JSON.', 'csv-to-json', true, 148, '/tools/csv-to-json', 'CSV', false, false),
  ('csv-to-jsonlines', 'CSV to JSON Lines', 'Convert CSV to JSON Lines.', 'csv-to-jsonlines', true, 149, '/tools/csv-to-jsonlines', 'CSV', false, false),
  ('csv-to-latex', 'CSV to LaTeX', 'Convert CSV to LaTeX.', 'csv-to-latex', true, 150, '/tools/csv-to-latex', 'CSV', false, false),
  ('csv-to-magic', 'CSV to Magic', 'Convert CSV to Magic.', 'csv-to-magic', true, 151, '/tools/csv-to-magic', 'CSV', false, false),
  ('csv-to-markdown', 'CSV to Markdown', 'Convert CSV to Markdown Table.', 'csv-to-markdown', true, 152, '/tools/csv-to-markdown', 'CSV', false, false),
  ('csv-to-matlab', 'CSV to MATLAB', 'Convert CSV to MATLAB.', 'csv-to-matlab', true, 153, '/tools/csv-to-matlab', 'CSV', false, false),
  ('csv-to-mediawiki', 'CSV to MediaWiki', 'Convert CSV to MediaWiki Table.', 'csv-to-mediawiki', true, 154, '/tools/csv-to-mediawiki', 'CSV', false, false),
  ('csv-to-pandasdataframe', 'CSV to Pandas', 'Convert CSV to Pandas DataFrame.', 'csv-to-pandasdataframe', true, 155, '/tools/csv-to-pandasdataframe', 'CSV', false, false),
  ('csv-to-pdf', 'CSV to PDF', 'Convert CSV to PDF.', 'csv-to-pdf', true, 156, '/tools/csv-to-pdf', 'CSV', false, false),
  ('csv-to-php', 'CSV to PHP', 'Convert CSV to PHP Array.', 'csv-to-php', true, 157, '/tools/csv-to-php', 'CSV', false, false),
  ('csv-to-png', 'CSV to PNG', 'Convert CSV to PNG image.', 'csv-to-png', true, 158, '/tools/csv-to-png', 'CSV', false, false),
  ('csv-to-protobuf', 'CSV to Protobuf', 'Convert CSV to Protobuf.', 'csv-to-protobuf', true, 159, '/tools/csv-to-protobuf', 'CSV', false, false),
  ('csv-to-qlik', 'CSV to Qlik', 'Convert CSV to Qlik.', 'csv-to-qlik', true, 160, '/tools/csv-to-qlik', 'CSV', false, false),
  ('csv-to-rdataframe', 'CSV to R DataFrame', 'Convert CSV to R DataFrame.', 'csv-to-rdataframe', true, 161, '/tools/csv-to-rdataframe', 'CSV', false, false),
  ('csv-to-rdf', 'CSV to RDF', 'Convert CSV to RDF.', 'csv-to-rdf', true, 162, '/tools/csv-to-rdf', 'CSV', false, false),
  ('csv-to-restructuredtext', 'CSV to reStructuredText', 'Convert CSV to reStructuredText.', 'csv-to-restructuredtext', true, 163, '/tools/csv-to-restructuredtext', 'CSV', false, false),
  ('csv-to-ruby', 'CSV to Ruby', 'Convert CSV to Ruby.', 'csv-to-ruby', true, 164, '/tools/csv-to-ruby', 'CSV', false, false),
  ('csv-to-sql', 'CSV to SQL', 'Convert CSV to SQL.', 'csv-to-sql', true, 165, '/tools/csv-to-sql', 'CSV', false, false),
  ('csv-to-textile', 'CSV to Textile', 'Convert CSV to Textile.', 'csv-to-textile', true, 166, '/tools/csv-to-textile', 'CSV', false, false),
  ('csv-to-toml', 'CSV to TOML', 'Convert CSV to TOML.', 'csv-to-toml', true, 167, '/tools/csv-to-toml', 'CSV', false, false),
  ('csv-to-tracwiki', 'CSV to TracWiki', 'Convert CSV to TracWiki.', 'csv-to-tracwiki', true, 168, '/tools/csv-to-tracwiki', 'CSV', false, false),
  ('csv-to-xml', 'CSV to XML', 'Convert CSV to XML.', 'csv-to-xml', true, 169, '/tools/csv-to-xml', 'CSV', false, false),
  ('csv-to-yaml', 'CSV to YAML', 'Convert CSV to YAML.', 'csv-to-yaml', true, 170, '/tools/csv-to-yaml', 'CSV', false, false),
  ('markdown-to-actionscript', 'Markdown to ActionScript', 'Convert Markdown to ActionScript.', 'markdown-to-actionscript', true, 171, '/tools/markdown-to-actionscript', 'Markdown', false, false),
  ('markdown-to-ascii', 'Markdown to ASCII', 'Convert Markdown to ASCII.', 'markdown-to-ascii', true, 172, '/tools/markdown-to-ascii', 'Markdown', false, false),
  ('markdown-to-asciidoc', 'Markdown to AsciiDoc', 'Convert Markdown to AsciiDoc.', 'markdown-to-asciidoc', true, 173, '/tools/markdown-to-asciidoc', 'Markdown', false, false),
  ('markdown-to-asp', 'Markdown to ASP', 'Convert Markdown to ASP.', 'markdown-to-asp', true, 174, '/tools/markdown-to-asp', 'Markdown', false, false),
  ('markdown-to-avro', 'Markdown to Avro', 'Convert Markdown to Avro.', 'markdown-to-avro', true, 175, '/tools/markdown-to-avro', 'Markdown', false, false),
  ('markdown-to-bbcode', 'Markdown to BBCode', 'Convert Markdown to BBCode.', 'markdown-to-bbcode', true, 176, '/tools/markdown-to-bbcode', 'Markdown', false, false),
  ('markdown-to-csv', 'Markdown to CSV', 'Convert Markdown Table to CSV.', 'markdown-to-csv', true, 177, '/tools/markdown-to-csv', 'Markdown', false, false),
  ('markdown-to-dax', 'Markdown to DAX', 'Convert Markdown to DAX.', 'markdown-to-dax', true, 178, '/tools/markdown-to-dax', 'Markdown', false, false),
  ('markdown-to-excel', 'Markdown to Excel', 'Convert Markdown Table to Excel.', 'markdown-to-excel', true, 179, '/tools/markdown-to-excel', 'Markdown', false, false),
  ('markdown-to-firebase', 'Markdown to Firebase', 'Convert Markdown to Firebase.', 'markdown-to-firebase', true, 180, '/tools/markdown-to-firebase', 'Markdown', false, false),
  ('markdown-to-html', 'Markdown to HTML', 'Chuyển đổi Markdown sang HTML với Live Preview.', 'markdown-to-html', true, 181, '/tools/markdown-to-html', 'Markdown', true, false),
  ('markdown-to-ini', 'Markdown to INI', 'Convert Markdown to INI.', 'markdown-to-ini', true, 182, '/tools/markdown-to-ini', 'Markdown', false, false),
  ('markdown-to-jira', 'Markdown to Jira', 'Convert Markdown to Jira.', 'markdown-to-jira', true, 183, '/tools/markdown-to-jira', 'Markdown', false, false),
  ('markdown-to-jpeg', 'Markdown to JPEG', 'Convert Markdown to JPEG (Image).', 'markdown-to-jpeg', true, 184, '/tools/markdown-to-jpeg', 'Markdown', false, false),
  ('markdown-to-json', 'Markdown to JSON', 'Convert Markdown Table to JSON.', 'markdown-to-json', true, 185, '/tools/markdown-to-json', 'Markdown', false, false),
  ('markdown-to-jsonlines', 'Markdown to JSON Lines', 'Convert Markdown to JSON Lines.', 'markdown-to-jsonlines', true, 186, '/tools/markdown-to-jsonlines', 'Markdown', false, false),
  ('markdown-to-latex', 'Markdown to LaTeX', 'Convert Markdown to LaTeX.', 'markdown-to-latex', true, 187, '/tools/markdown-to-latex', 'Markdown', false, false),
  ('markdown-to-magic', 'Markdown to Magic', 'Convert Markdown to Magic.', 'markdown-to-magic', true, 188, '/tools/markdown-to-magic', 'Markdown', false, false),
  ('markdown-to-markdown', 'Markdown to Markdown', 'Beautify/Format Markdown.', 'markdown-to-markdown', true, 189, '/tools/markdown-to-markdown', 'Markdown', false, false),
  ('markdown-to-matlab', 'Markdown to MATLAB', 'Convert Markdown to MATLAB.', 'markdown-to-matlab', true, 190, '/tools/markdown-to-matlab', 'Markdown', false, false),
  ('markdown-to-mediawiki', 'Markdown to MediaWiki', 'Convert Markdown to MediaWiki.', 'markdown-to-mediawiki', true, 191, '/tools/markdown-to-mediawiki', 'Markdown', false, false),
  ('markdown-to-pandasdataframe', 'Markdown to Pandas', 'Convert Markdown Table to Pandas.', 'markdown-to-pandasdataframe', true, 192, '/tools/markdown-to-pandasdataframe', 'Markdown', false, false),
  ('markdown-to-pdf', 'Markdown to PDF', 'Convert Markdown to PDF.', 'markdown-to-pdf', true, 193, '/tools/markdown-to-pdf', 'Markdown', false, false),
  ('markdown-to-php', 'Markdown to PHP', 'Convert Markdown to PHP.', 'markdown-to-php', true, 194, '/tools/markdown-to-php', 'Markdown', false, false),
  ('markdown-to-png', 'Markdown to PNG', 'Convert Markdown to PNG (Image).', 'markdown-to-png', true, 195, '/tools/markdown-to-png', 'Markdown', false, false),
  ('markdown-to-protobuf', 'Markdown to Protobuf', 'Convert Markdown to Protobuf.', 'markdown-to-protobuf', true, 196, '/tools/markdown-to-protobuf', 'Markdown', false, false),
  ('markdown-to-qlik', 'Markdown to Qlik', 'Convert Markdown to Qlik.', 'markdown-to-qlik', true, 197, '/tools/markdown-to-qlik', 'Markdown', false, false),
  ('markdown-to-rdataframe', 'Markdown to R DataFrame', 'Convert Markdown to R DataFrame.', 'markdown-to-rdataframe', true, 198, '/tools/markdown-to-rdataframe', 'Markdown', false, false),
  ('markdown-to-rdf', 'Markdown to RDF', 'Convert Markdown to RDF.', 'markdown-to-rdf', true, 199, '/tools/markdown-to-rdf', 'Markdown', false, false),
  ('markdown-to-restructuredtext', 'Markdown to reStructuredText', 'Convert Markdown to reStructuredText.', 'markdown-to-restructuredtext', true, 200, '/tools/markdown-to-restructuredtext', 'Markdown', false, false),
  ('markdown-to-ruby', 'Markdown to Ruby', 'Convert Markdown to Ruby.', 'markdown-to-ruby', true, 201, '/tools/markdown-to-ruby', 'Markdown', false, false),
  ('markdown-to-sql', 'Markdown to SQL', 'Convert Markdown Table to SQL.', 'markdown-to-sql', true, 202, '/tools/markdown-to-sql', 'Markdown', false, false),
  ('markdown-to-textile', 'Markdown to Textile', 'Convert Markdown to Textile.', 'markdown-to-textile', true, 203, '/tools/markdown-to-textile', 'Markdown', false, false),
  ('markdown-to-toml', 'Markdown to TOML', 'Convert Markdown to TOML.', 'markdown-to-toml', true, 204, '/tools/markdown-to-toml', 'Markdown', false, false),
  ('markdown-to-tracwiki', 'Markdown to TracWiki', 'Convert Markdown to TracWiki.', 'markdown-to-tracwiki', true, 205, '/tools/markdown-to-tracwiki', 'Markdown', false, false),
  ('markdown-to-xml', 'Markdown to XML', 'Convert Markdown to XML.', 'markdown-to-xml', true, 206, '/tools/markdown-to-xml', 'Markdown', false, false),
  ('markdown-to-yaml', 'Markdown to YAML', 'Convert Markdown to YAML.', 'markdown-to-yaml', true, 207, '/tools/markdown-to-yaml', 'Markdown', false, false),
  ('html-to-actionscript', 'HTML to ActionScript', 'Convert HTML to ActionScript.', 'html-to-actionscript', true, 208, '/tools/html-to-actionscript', 'HTML', false, false),
  ('html-to-ascii', 'HTML to ASCII', 'Convert HTML to ASCII.', 'html-to-ascii', true, 209, '/tools/html-to-ascii', 'HTML', false, false),
  ('html-to-asciidoc', 'HTML to AsciiDoc', 'Convert HTML to AsciiDoc.', 'html-to-asciidoc', true, 210, '/tools/html-to-asciidoc', 'HTML', false, false),
  ('html-to-asp', 'HTML to ASP', 'Convert HTML to ASP.', 'html-to-asp', true, 211, '/tools/html-to-asp', 'HTML', false, false),
  ('html-to-avro', 'HTML to Avro', 'Convert HTML to Avro.', 'html-to-avro', true, 212, '/tools/html-to-avro', 'HTML', false, false),
  ('html-to-bbcode', 'HTML to BBCode', 'Convert HTML to BBCode.', 'html-to-bbcode', true, 213, '/tools/html-to-bbcode', 'HTML', false, false),
  ('html-to-csv', 'HTML to CSV', 'Convert HTML Table to CSV.', 'html-to-csv', true, 214, '/tools/html-to-csv', 'HTML', false, false),
  ('html-to-dax', 'HTML to DAX', 'Convert HTML to DAX.', 'html-to-dax', true, 215, '/tools/html-to-dax', 'HTML', false, false),
  ('html-to-excel', 'HTML to Excel', 'Convert HTML Table to Excel.', 'html-to-excel', true, 216, '/tools/html-to-excel', 'HTML', false, false),
  ('html-to-firebase', 'HTML to Firebase', 'Convert HTML to Firebase.', 'html-to-firebase', true, 217, '/tools/html-to-firebase', 'HTML', false, false),
  ('html-to-html', 'HTML to HTML', 'Beautify/Format HTML.', 'html-to-html', true, 218, '/tools/html-to-html', 'HTML', false, false),
  ('html-to-ini', 'HTML to INI', 'Convert HTML to INI.', 'html-to-ini', true, 219, '/tools/html-to-ini', 'HTML', false, false),
  ('html-to-jira', 'HTML to Jira', 'Convert HTML to Jira.', 'html-to-jira', true, 220, '/tools/html-to-jira', 'HTML', false, false),
  ('html-to-jpeg', 'HTML to JPEG', 'Convert HTML to JPEG (Image).', 'html-to-jpeg', true, 221, '/tools/html-to-jpeg', 'HTML', false, false),
  ('html-to-json', 'HTML to JSON', 'Convert HTML Table to JSON.', 'html-to-json', true, 222, '/tools/html-to-json', 'HTML', false, false),
  ('html-to-jsonlines', 'HTML to JSON Lines', 'Convert HTML to JSON Lines.', 'html-to-jsonlines', true, 223, '/tools/html-to-jsonlines', 'HTML', false, false),
  ('html-to-latex', 'HTML to LaTeX', 'Convert HTML to LaTeX.', 'html-to-latex', true, 224, '/tools/html-to-latex', 'HTML', false, false),
  ('html-to-magic', 'HTML to Magic', 'Convert HTML to Magic.', 'html-to-magic', true, 225, '/tools/html-to-magic', 'HTML', false, false),
  ('html-to-markdown', 'HTML to Markdown', 'Convert HTML to Markdown.', 'html-to-markdown', true, 226, '/tools/html-to-markdown', 'HTML', false, false),
  ('html-to-matlab', 'HTML to MATLAB', 'Convert HTML to MATLAB.', 'html-to-matlab', true, 227, '/tools/html-to-matlab', 'HTML', false, false),
  ('html-to-mediawiki', 'HTML to MediaWiki', 'Convert HTML to MediaWiki.', 'html-to-mediawiki', true, 228, '/tools/html-to-mediawiki', 'HTML', false, false),
  ('html-to-pandasdataframe', 'HTML to Pandas', 'Convert HTML Table to Pandas.', 'html-to-pandasdataframe', true, 229, '/tools/html-to-pandasdataframe', 'HTML', false, false),
  ('html-to-pdf', 'HTML to PDF', 'Convert HTML to PDF.', 'html-to-pdf', true, 230, '/tools/html-to-pdf', 'HTML', false, false),
  ('html-to-php', 'HTML to PHP', 'Convert HTML to PHP.', 'html-to-php', true, 231, '/tools/html-to-php', 'HTML', false, false),
  ('html-to-png', 'HTML to PNG', 'Convert HTML to PNG (Image).', 'html-to-png', true, 232, '/tools/html-to-png', 'HTML', false, false),
  ('html-to-protobuf', 'HTML to Protobuf', 'Convert HTML to Protobuf.', 'html-to-protobuf', true, 233, '/tools/html-to-protobuf', 'HTML', false, false),
  ('html-to-qlik', 'HTML to Qlik', 'Convert HTML to Qlik.', 'html-to-qlik', true, 234, '/tools/html-to-qlik', 'HTML', false, false),
  ('html-to-rdataframe', 'HTML to R DataFrame', 'Convert HTML to R DataFrame.', 'html-to-rdataframe', true, 235, '/tools/html-to-rdataframe', 'HTML', false, false),
  ('html-to-rdf', 'HTML to RDF', 'Convert HTML to RDF.', 'html-to-rdf', true, 236, '/tools/html-to-rdf', 'HTML', false, false),
  ('html-to-restructuredtext', 'HTML to reStructuredText', 'Convert HTML to reStructuredText.', 'html-to-restructuredtext', true, 237, '/tools/html-to-restructuredtext', 'HTML', false, false),
  ('html-to-ruby', 'HTML to Ruby', 'Convert HTML to Ruby.', 'html-to-ruby', true, 238, '/tools/html-to-ruby', 'HTML', false, false),
  ('html-to-sql', 'HTML to SQL', 'Convert HTML Table to SQL.', 'html-to-sql', true, 239, '/tools/html-to-sql', 'HTML', false, false),
  ('html-to-textile', 'HTML to Textile', 'Convert HTML to Textile.', 'html-to-textile', true, 240, '/tools/html-to-textile', 'HTML', false, false),
  ('html-to-toml', 'HTML to TOML', 'Convert HTML to TOML.', 'html-to-toml', true, 241, '/tools/html-to-toml', 'HTML', false, false),
  ('html-to-tracwiki', 'HTML to TracWiki', 'Convert HTML to TracWiki.', 'html-to-tracwiki', true, 242, '/tools/html-to-tracwiki', 'HTML', false, false),
  ('html-to-xml', 'HTML to XML', 'Convert HTML to XML.', 'html-to-xml', true, 243, '/tools/html-to-xml', 'HTML', false, false),
  ('html-to-yaml', 'HTML to YAML', 'Convert HTML to YAML.', 'html-to-yaml', true, 244, '/tools/html-to-yaml', 'HTML', false, false),
  ('sql-to-actionscript', 'SQL to ActionScript', 'Convert SQL to ActionScript.', 'sql-to-actionscript', true, 245, '/tools/sql-to-actionscript', 'SQL', false, false),
  ('sql-to-ascii', 'SQL to ASCII', 'Convert SQL to ASCII.', 'sql-to-ascii', true, 246, '/tools/sql-to-ascii', 'SQL', false, false),
  ('sql-to-asciidoc', 'SQL to AsciiDoc', 'Convert SQL to AsciiDoc.', 'sql-to-asciidoc', true, 247, '/tools/sql-to-asciidoc', 'SQL', false, false),
  ('sql-to-asp', 'SQL to ASP', 'Convert SQL to ASP.', 'sql-to-asp', true, 248, '/tools/sql-to-asp', 'SQL', false, false),
  ('sql-to-avro', 'SQL to Avro', 'Convert SQL to Avro.', 'sql-to-avro', true, 249, '/tools/sql-to-avro', 'SQL', false, false),
  ('sql-to-bbcode', 'SQL to BBCode', 'Convert SQL to BBCode.', 'sql-to-bbcode', true, 250, '/tools/sql-to-bbcode', 'SQL', false, false),
  ('sql-to-csv', 'SQL to CSV', 'Convert SQL to CSV.', 'sql-to-csv', true, 251, '/tools/sql-to-csv', 'SQL', false, false),
  ('sql-to-dax', 'SQL to DAX', 'Convert SQL to DAX.', 'sql-to-dax', true, 252, '/tools/sql-to-dax', 'SQL', false, false),
  ('sql-to-excel', 'SQL to Excel', 'Convert SQL to Excel.', 'sql-to-excel', true, 253, '/tools/sql-to-excel', 'SQL', false, false),
  ('sql-to-firebase', 'SQL to Firebase', 'Convert SQL to Firebase.', 'sql-to-firebase', true, 254, '/tools/sql-to-firebase', 'SQL', false, false),
  ('sql-to-html', 'SQL to HTML', 'Convert SQL to HTML.', 'sql-to-html', true, 255, '/tools/sql-to-html', 'SQL', false, false),
  ('sql-to-ini', 'SQL to INI', 'Convert SQL to INI.', 'sql-to-ini', true, 256, '/tools/sql-to-ini', 'SQL', false, false),
  ('sql-to-jira', 'SQL to Jira', 'Convert SQL to Jira.', 'sql-to-jira', true, 257, '/tools/sql-to-jira', 'SQL', false, false),
  ('sql-to-jpeg', 'SQL to JPEG', 'Convert SQL to JPEG (Image).', 'sql-to-jpeg', true, 258, '/tools/sql-to-jpeg', 'SQL', false, false),
  ('sql-to-json', 'SQL to JSON', 'Convert SQL to JSON.', 'sql-to-json', true, 259, '/tools/sql-to-json', 'SQL', false, false),
  ('sql-to-jsonlines', 'SQL to JSON Lines', 'Convert SQL to JSON Lines.', 'sql-to-jsonlines', true, 260, '/tools/sql-to-jsonlines', 'SQL', false, false),
  ('sql-to-latex', 'SQL to LaTeX', 'Convert SQL to LaTeX.', 'sql-to-latex', true, 261, '/tools/sql-to-latex', 'SQL', false, false),
  ('sql-to-magic', 'SQL to Magic', 'Convert SQL to Magic.', 'sql-to-magic', true, 262, '/tools/sql-to-magic', 'SQL', false, false),
  ('sql-to-markdown', 'SQL to Markdown', 'Convert SQL to Markdown.', 'sql-to-markdown', true, 263, '/tools/sql-to-markdown', 'SQL', false, false),
  ('sql-to-matlab', 'SQL to MATLAB', 'Convert SQL to MATLAB.', 'sql-to-matlab', true, 264, '/tools/sql-to-matlab', 'SQL', false, false),
  ('sql-to-mediawiki', 'SQL to MediaWiki', 'Convert SQL to MediaWiki.', 'sql-to-mediawiki', true, 265, '/tools/sql-to-mediawiki', 'SQL', false, false),
  ('sql-to-pandasdataframe', 'SQL to Pandas', 'Convert SQL to Pandas.', 'sql-to-pandasdataframe', true, 266, '/tools/sql-to-pandasdataframe', 'SQL', false, false),
  ('sql-to-pdf', 'SQL to PDF', 'Convert SQL to PDF.', 'sql-to-pdf', true, 267, '/tools/sql-to-pdf', 'SQL', false, false),
  ('sql-to-php', 'SQL to PHP', 'Convert SQL to PHP.', 'sql-to-php', true, 268, '/tools/sql-to-php', 'SQL', false, false),
  ('sql-to-png', 'SQL to PNG', 'Convert SQL to PNG (Image).', 'sql-to-png', true, 269, '/tools/sql-to-png', 'SQL', false, false),
  ('sql-to-protobuf', 'SQL to Protobuf', 'Convert SQL to Protobuf.', 'sql-to-protobuf', true, 270, '/tools/sql-to-protobuf', 'SQL', false, false),
  ('sql-to-qlik', 'SQL to Qlik', 'Convert SQL to Qlik.', 'sql-to-qlik', true, 271, '/tools/sql-to-qlik', 'SQL', false, false),
  ('sql-to-rdataframe', 'SQL to R DataFrame', 'Convert SQL to R DataFrame.', 'sql-to-rdataframe', true, 272, '/tools/sql-to-rdataframe', 'SQL', false, false),
  ('sql-to-rdf', 'SQL to RDF', 'Convert SQL to RDF.', 'sql-to-rdf', true, 273, '/tools/sql-to-rdf', 'SQL', false, false),
  ('sql-to-restructuredtext', 'SQL to reStructuredText', 'Convert SQL to reStructuredText.', 'sql-to-restructuredtext', true, 274, '/tools/sql-to-restructuredtext', 'SQL', false, false),
  ('sql-to-ruby', 'SQL to Ruby', 'Convert SQL to Ruby.', 'sql-to-ruby', true, 275, '/tools/sql-to-ruby', 'SQL', false, false),
  ('sql-to-sql', 'SQL to SQL', 'Format/Clean SQL.', 'sql-to-sql', true, 276, '/tools/sql-to-sql', 'SQL', false, false),
  ('sql-to-textile', 'SQL to Textile', 'Convert SQL to Textile.', 'sql-to-textile', true, 277, '/tools/sql-to-textile', 'SQL', false, false),
  ('sql-to-toml', 'SQL to TOML', 'Convert SQL to TOML.', 'sql-to-toml', true, 278, '/tools/sql-to-toml', 'SQL', false, false),
  ('sql-to-tracwiki', 'SQL to TracWiki', 'Convert SQL to TracWiki.', 'sql-to-tracwiki', true, 279, '/tools/sql-to-tracwiki', 'SQL', false, false),
  ('sql-to-xml', 'SQL to XML', 'Convert SQL to XML.', 'sql-to-xml', true, 280, '/tools/sql-to-xml', 'SQL', false, false),
  ('sql-to-yaml', 'SQL to YAML', 'Convert SQL to YAML.', 'sql-to-yaml', true, 281, '/tools/sql-to-yaml', 'SQL', false, false),
  ('latex-to-actionscript', 'LaTeX to ActionScript', 'Convert LaTeX to ActionScript.', 'latex-to-actionscript', true, 282, '/tools/latex-to-actionscript', 'LaTeX', false, false),
  ('latex-to-ascii', 'LaTeX to ASCII', 'Convert LaTeX to ASCII.', 'latex-to-ascii', true, 283, '/tools/latex-to-ascii', 'LaTeX', false, false),
  ('latex-to-asciidoc', 'LaTeX to AsciiDoc', 'Convert LaTeX to AsciiDoc.', 'latex-to-asciidoc', true, 284, '/tools/latex-to-asciidoc', 'LaTeX', false, false),
  ('latex-to-asp', 'LaTeX to ASP', 'Convert LaTeX to ASP.', 'latex-to-asp', true, 285, '/tools/latex-to-asp', 'LaTeX', false, false),
  ('latex-to-avro', 'LaTeX to Avro', 'Convert LaTeX to Avro.', 'latex-to-avro', true, 286, '/tools/latex-to-avro', 'LaTeX', false, false),
  ('latex-to-bbcode', 'LaTeX to BBCode', 'Convert LaTeX to BBCode.', 'latex-to-bbcode', true, 287, '/tools/latex-to-bbcode', 'LaTeX', false, false),
  ('latex-to-csv', 'LaTeX to CSV', 'Convert LaTeX Table to CSV.', 'latex-to-csv', true, 288, '/tools/latex-to-csv', 'LaTeX', false, false),
  ('latex-to-dax', 'LaTeX to DAX', 'Convert LaTeX to DAX.', 'latex-to-dax', true, 289, '/tools/latex-to-dax', 'LaTeX', false, false),
  ('latex-to-excel', 'LaTeX to Excel', 'Convert LaTeX Table to Excel.', 'latex-to-excel', true, 290, '/tools/latex-to-excel', 'LaTeX', false, false),
  ('latex-to-firebase', 'LaTeX to Firebase', 'Convert LaTeX to Firebase.', 'latex-to-firebase', true, 291, '/tools/latex-to-firebase', 'LaTeX', false, false),
  ('latex-to-html', 'LaTeX to HTML', 'Convert LaTeX to HTML.', 'latex-to-html', true, 292, '/tools/latex-to-html', 'LaTeX', false, false),
  ('latex-to-ini', 'LaTeX to INI', 'Convert LaTeX to INI.', 'latex-to-ini', true, 293, '/tools/latex-to-ini', 'LaTeX', false, false),
  ('latex-to-jira', 'LaTeX to Jira', 'Convert LaTeX to Jira.', 'latex-to-jira', true, 294, '/tools/latex-to-jira', 'LaTeX', false, false),
  ('latex-to-jpeg', 'LaTeX to JPEG', 'Convert LaTeX to JPEG (Image).', 'latex-to-jpeg', true, 295, '/tools/latex-to-jpeg', 'LaTeX', false, false),
  ('latex-to-json', 'LaTeX to JSON', 'Convert LaTeX Table to JSON.', 'latex-to-json', true, 296, '/tools/latex-to-json', 'LaTeX', false, false),
  ('latex-to-jsonlines', 'LaTeX to JSON Lines', 'Convert LaTeX to JSON Lines.', 'latex-to-jsonlines', true, 297, '/tools/latex-to-jsonlines', 'LaTeX', false, false),
  ('latex-to-latex', 'LaTeX to LaTeX', 'Format/Beautify LaTeX.', 'latex-to-latex', true, 298, '/tools/latex-to-latex', 'LaTeX', false, false),
  ('latex-to-magic', 'LaTeX to Magic', 'Convert LaTeX to Magic.', 'latex-to-magic', true, 299, '/tools/latex-to-magic', 'LaTeX', false, false),
  ('latex-to-markdown', 'LaTeX to Markdown', 'Convert LaTeX to Markdown.', 'latex-to-markdown', true, 300, '/tools/latex-to-markdown', 'LaTeX', false, false),
  ('latex-to-matlab', 'LaTeX to MATLAB', 'Convert LaTeX to MATLAB.', 'latex-to-matlab', true, 301, '/tools/latex-to-matlab', 'LaTeX', false, false),
  ('latex-to-mediawiki', 'LaTeX to MediaWiki', 'Convert LaTeX to MediaWiki.', 'latex-to-mediawiki', true, 302, '/tools/latex-to-mediawiki', 'LaTeX', false, false),
  ('latex-to-pandasdataframe', 'LaTeX to Pandas', 'Convert LaTeX Table to Pandas.', 'latex-to-pandasdataframe', true, 303, '/tools/latex-to-pandasdataframe', 'LaTeX', false, false),
  ('latex-to-pdf', 'LaTeX to PDF', 'Convert LaTeX to PDF.', 'latex-to-pdf', true, 304, '/tools/latex-to-pdf', 'LaTeX', false, false),
  ('latex-to-php', 'LaTeX to PHP', 'Convert LaTeX to PHP.', 'latex-to-php', true, 305, '/tools/latex-to-php', 'LaTeX', false, false),
  ('latex-to-png', 'LaTeX to PNG', 'Convert LaTeX to PNG (Image).', 'latex-to-png', true, 306, '/tools/latex-to-png', 'LaTeX', false, false),
  ('latex-to-protobuf', 'LaTeX to Protobuf', 'Convert LaTeX to Protobuf.', 'latex-to-protobuf', true, 307, '/tools/latex-to-protobuf', 'LaTeX', false, false),
  ('latex-to-qlik', 'LaTeX to Qlik', 'Convert LaTeX to Qlik.', 'latex-to-qlik', true, 308, '/tools/latex-to-qlik', 'LaTeX', false, false),
  ('latex-to-rdataframe', 'LaTeX to R DataFrame', 'Convert LaTeX to R DataFrame.', 'latex-to-rdataframe', true, 309, '/tools/latex-to-rdataframe', 'LaTeX', false, false),
  ('latex-to-rdf', 'LaTeX to RDF', 'Convert LaTeX to RDF.', 'latex-to-rdf', true, 310, '/tools/latex-to-rdf', 'LaTeX', false, false),
  ('latex-to-restructuredtext', 'LaTeX to reStructuredText', 'Convert LaTeX to reStructuredText.', 'latex-to-restructuredtext', true, 311, '/tools/latex-to-restructuredtext', 'LaTeX', false, false),
  ('latex-to-ruby', 'LaTeX to Ruby', 'Convert LaTeX to Ruby.', 'latex-to-ruby', true, 312, '/tools/latex-to-ruby', 'LaTeX', false, false),
  ('latex-to-sql', 'LaTeX to SQL', 'Convert LaTeX Table to SQL.', 'latex-to-sql', true, 313, '/tools/latex-to-sql', 'LaTeX', false, false),
  ('latex-to-textile', 'LaTeX to Textile', 'Convert LaTeX to Textile.', 'latex-to-textile', true, 314, '/tools/latex-to-textile', 'LaTeX', false, false),
  ('latex-to-toml', 'LaTeX to TOML', 'Convert LaTeX to TOML.', 'latex-to-toml', true, 315, '/tools/latex-to-toml', 'LaTeX', false, false),
  ('latex-to-tracwiki', 'LaTeX to TracWiki', 'Convert LaTeX to TracWiki.', 'latex-to-tracwiki', true, 316, '/tools/latex-to-tracwiki', 'LaTeX', false, false),
  ('latex-to-xml', 'LaTeX to XML', 'Convert LaTeX to XML.', 'latex-to-xml', true, 317, '/tools/latex-to-xml', 'LaTeX', false, false),
  ('latex-to-yaml', 'LaTeX to YAML', 'Convert LaTeX to YAML.', 'latex-to-yaml', true, 318, '/tools/latex-to-yaml', 'LaTeX', false, false),
  ('xml-to-actionscript', 'XML to ActionScript', 'Convert XML to ActionScript.', 'xml-to-actionscript', true, 319, '/tools/xml-to-actionscript', 'XML', false, false),
  ('xml-to-ascii', 'XML to ASCII', 'Convert XML to ASCII.', 'xml-to-ascii', true, 320, '/tools/xml-to-ascii', 'XML', false, false),
  ('xml-to-asciidoc', 'XML to AsciiDoc', 'Convert XML to AsciiDoc.', 'xml-to-asciidoc', true, 321, '/tools/xml-to-asciidoc', 'XML', false, false),
  ('xml-to-asp', 'XML to ASP', 'Convert XML to ASP.', 'xml-to-asp', true, 322, '/tools/xml-to-asp', 'XML', false, false),
  ('xml-to-avro', 'XML to Avro', 'Convert XML to Avro.', 'xml-to-avro', true, 323, '/tools/xml-to-avro', 'XML', false, false),
  ('xml-to-bbcode', 'XML to BBCode', 'Convert XML to BBCode.', 'xml-to-bbcode', true, 324, '/tools/xml-to-bbcode', 'XML', false, false),
  ('xml-to-csv', 'XML to CSV', 'Convert XML to CSV.', 'xml-to-csv', true, 325, '/tools/xml-to-csv', 'XML', false, false),
  ('xml-to-dax', 'XML to DAX', 'Convert XML to DAX.', 'xml-to-dax', true, 326, '/tools/xml-to-dax', 'XML', false, false),
  ('xml-to-excel', 'XML to Excel', 'Convert XML to Excel.', 'xml-to-excel', true, 327, '/tools/xml-to-excel', 'XML', false, false),
  ('xml-to-firebase', 'XML to Firebase', 'Convert XML to Firebase.', 'xml-to-firebase', true, 328, '/tools/xml-to-firebase', 'XML', false, false),
  ('xml-to-html', 'XML to HTML', 'Convert XML to HTML.', 'xml-to-html', true, 329, '/tools/xml-to-html', 'XML', false, false),
  ('xml-to-ini', 'XML to INI', 'Convert XML to INI.', 'xml-to-ini', true, 330, '/tools/xml-to-ini', 'XML', false, false),
  ('xml-to-jira', 'XML to Jira', 'Convert XML to Jira.', 'xml-to-jira', true, 331, '/tools/xml-to-jira', 'XML', false, false),
  ('xml-to-jpeg', 'XML to JPEG', 'Convert XML to JPEG (Image).', 'xml-to-jpeg', true, 332, '/tools/xml-to-jpeg', 'XML', false, false),
  ('xml-to-json', 'XML to JSON', 'Convert XML to JSON.', 'xml-to-json', true, 333, '/tools/xml-to-json', 'XML', false, false),
  ('xml-to-jsonlines', 'XML to JSON Lines', 'Convert XML to JSON Lines.', 'xml-to-jsonlines', true, 334, '/tools/xml-to-jsonlines', 'XML', false, false),
  ('xml-to-latex', 'XML to LaTeX', 'Convert XML to LaTeX.', 'xml-to-latex', true, 335, '/tools/xml-to-latex', 'XML', false, false),
  ('xml-to-magic', 'XML to Magic', 'Convert XML to Magic.', 'xml-to-magic', true, 336, '/tools/xml-to-magic', 'XML', false, false),
  ('xml-to-markdown', 'XML to Markdown', 'Convert XML to Markdown.', 'xml-to-markdown', true, 337, '/tools/xml-to-markdown', 'XML', false, false),
  ('xml-to-matlab', 'XML to MATLAB', 'Convert XML to MATLAB.', 'xml-to-matlab', true, 338, '/tools/xml-to-matlab', 'XML', false, false),
  ('xml-to-mediawiki', 'XML to MediaWiki', 'Convert XML to MediaWiki.', 'xml-to-mediawiki', true, 339, '/tools/xml-to-mediawiki', 'XML', false, false),
  ('xml-to-pandasdataframe', 'XML to Pandas', 'Convert XML to Pandas.', 'xml-to-pandasdataframe', true, 340, '/tools/xml-to-pandasdataframe', 'XML', false, false),
  ('xml-to-pdf', 'XML to PDF', 'Convert XML to PDF.', 'xml-to-pdf', true, 341, '/tools/xml-to-pdf', 'XML', false, false),
  ('xml-to-php', 'XML to PHP', 'Convert XML to PHP.', 'xml-to-php', true, 342, '/tools/xml-to-php', 'XML', false, false),
  ('xml-to-png', 'XML to PNG', 'Convert XML to PNG (Image).', 'xml-to-png', true, 343, '/tools/xml-to-png', 'XML', false, false),
  ('xml-to-protobuf', 'XML to Protobuf', 'Convert XML to Protobuf.', 'xml-to-protobuf', true, 344, '/tools/xml-to-protobuf', 'XML', false, false),
  ('xml-to-qlik', 'XML to Qlik', 'Convert XML to Qlik.', 'xml-to-qlik', true, 345, '/tools/xml-to-qlik', 'XML', false, false),
  ('xml-to-rdataframe', 'XML to R DataFrame', 'Convert XML to R DataFrame.', 'xml-to-rdataframe', true, 346, '/tools/xml-to-rdataframe', 'XML', false, false),
  ('xml-to-rdf', 'XML to RDF', 'Convert XML to RDF.', 'xml-to-rdf', true, 347, '/tools/xml-to-rdf', 'XML', false, false),
  ('xml-to-restructuredtext', 'XML to reStructuredText', 'Convert XML to reStructuredText.', 'xml-to-restructuredtext', true, 348, '/tools/xml-to-restructuredtext', 'XML', false, false),
  ('xml-to-ruby', 'XML to Ruby', 'Convert XML to Ruby.', 'xml-to-ruby', true, 349, '/tools/xml-to-ruby', 'XML', false, false),
  ('xml-to-sql', 'XML to SQL', 'Convert XML to SQL.', 'xml-to-sql', true, 350, '/tools/xml-to-sql', 'XML', false, false),
  ('xml-to-textile', 'XML to Textile', 'Convert XML to Textile.', 'xml-to-textile', true, 351, '/tools/xml-to-textile', 'XML', false, false),
  ('xml-to-toml', 'XML to TOML', 'Convert XML to TOML.', 'xml-to-toml', true, 352, '/tools/xml-to-toml', 'XML', false, false),
  ('xml-to-tracwiki', 'XML to TracWiki', 'Convert XML to TracWiki.', 'xml-to-tracwiki', true, 353, '/tools/xml-to-tracwiki', 'XML', false, false),
  ('xml-to-xml', 'XML to XML', 'Format/Beautify XML.', 'xml-to-xml', true, 354, '/tools/xml-to-xml', 'XML', false, false),
  ('xml-to-yaml', 'XML to YAML', 'Convert XML to YAML.', 'xml-to-yaml', true, 355, '/tools/xml-to-yaml', 'XML', false, false),
  ('mysql-to-actionscript', 'MySQL to ActionScript', 'Convert MySQL to ActionScript.', 'mysql-to-actionscript', true, 356, '/tools/mysql-to-actionscript', 'MySQL', false, false),
  ('mysql-to-ascii', 'MySQL to ASCII', 'Convert MySQL to ASCII.', 'mysql-to-ascii', true, 357, '/tools/mysql-to-ascii', 'MySQL', false, false),
  ('mysql-to-asciidoc', 'MySQL to AsciiDoc', 'Convert MySQL to AsciiDoc.', 'mysql-to-asciidoc', true, 358, '/tools/mysql-to-asciidoc', 'MySQL', false, false),
  ('mysql-to-asp', 'MySQL to ASP', 'Convert MySQL to ASP.', 'mysql-to-asp', true, 359, '/tools/mysql-to-asp', 'MySQL', false, false),
  ('mysql-to-avro', 'MySQL to Avro', 'Convert MySQL to Avro.', 'mysql-to-avro', true, 360, '/tools/mysql-to-avro', 'MySQL', false, false),
  ('mysql-to-bbcode', 'MySQL to BBCode', 'Convert MySQL to BBCode.', 'mysql-to-bbcode', true, 361, '/tools/mysql-to-bbcode', 'MySQL', false, false),
  ('mysql-to-csv', 'MySQL to CSV', 'Convert MySQL to CSV.', 'mysql-to-csv', true, 362, '/tools/mysql-to-csv', 'MySQL', false, false),
  ('mysql-to-dax', 'MySQL to DAX', 'Convert MySQL to DAX.', 'mysql-to-dax', true, 363, '/tools/mysql-to-dax', 'MySQL', false, false),
  ('mysql-to-excel', 'MySQL to Excel', 'Convert MySQL to Excel.', 'mysql-to-excel', true, 364, '/tools/mysql-to-excel', 'MySQL', false, false),
  ('mysql-to-firebase', 'MySQL to Firebase', 'Convert MySQL to Firebase.', 'mysql-to-firebase', true, 365, '/tools/mysql-to-firebase', 'MySQL', false, false),
  ('mysql-to-html', 'MySQL to HTML', 'Convert MySQL to HTML.', 'mysql-to-html', true, 366, '/tools/mysql-to-html', 'MySQL', false, false),
  ('mysql-to-ini', 'MySQL to INI', 'Convert MySQL to INI.', 'mysql-to-ini', true, 367, '/tools/mysql-to-ini', 'MySQL', false, false),
  ('mysql-to-jira', 'MySQL to Jira', 'Convert MySQL to Jira.', 'mysql-to-jira', true, 368, '/tools/mysql-to-jira', 'MySQL', false, false),
  ('mysql-to-jpeg', 'MySQL to JPEG', 'Convert MySQL to JPEG (Image).', 'mysql-to-jpeg', true, 369, '/tools/mysql-to-jpeg', 'MySQL', false, false),
  ('mysql-to-json', 'MySQL to JSON', 'Convert MySQL to JSON.', 'mysql-to-json', true, 370, '/tools/mysql-to-json', 'MySQL', false, false),
  ('mysql-to-jsonlines', 'MySQL to JSON Lines', 'Convert MySQL to JSON Lines.', 'mysql-to-jsonlines', true, 371, '/tools/mysql-to-jsonlines', 'MySQL', false, false),
  ('mysql-to-latex', 'MySQL to LaTeX', 'Convert MySQL to LaTeX.', 'mysql-to-latex', true, 372, '/tools/mysql-to-latex', 'MySQL', false, false),
  ('mysql-to-magic', 'MySQL to Magic', 'Convert MySQL to Magic.', 'mysql-to-magic', true, 373, '/tools/mysql-to-magic', 'MySQL', false, false),
  ('mysql-to-markdown', 'MySQL to Markdown', 'Convert MySQL to Markdown.', 'mysql-to-markdown', true, 374, '/tools/mysql-to-markdown', 'MySQL', false, false),
  ('mysql-to-matlab', 'MySQL to MATLAB', 'Convert MySQL to MATLAB.', 'mysql-to-matlab', true, 375, '/tools/mysql-to-matlab', 'MySQL', false, false),
  ('mysql-to-mediawiki', 'MySQL to MediaWiki', 'Convert MySQL to MediaWiki.', 'mysql-to-mediawiki', true, 376, '/tools/mysql-to-mediawiki', 'MySQL', false, false),
  ('mysql-to-pandasdataframe', 'MySQL to Pandas', 'Convert MySQL to Pandas.', 'mysql-to-pandasdataframe', true, 377, '/tools/mysql-to-pandasdataframe', 'MySQL', false, false),
  ('mysql-to-pdf', 'MySQL to PDF', 'Convert MySQL to PDF.', 'mysql-to-pdf', true, 378, '/tools/mysql-to-pdf', 'MySQL', false, false),
  ('mysql-to-php', 'MySQL to PHP', 'Convert MySQL to PHP.', 'mysql-to-php', true, 379, '/tools/mysql-to-php', 'MySQL', false, false),
  ('mysql-to-png', 'MySQL to PNG', 'Convert MySQL to PNG (Image).', 'mysql-to-png', true, 380, '/tools/mysql-to-png', 'MySQL', false, false),
  ('mysql-to-protobuf', 'MySQL to Protobuf', 'Convert MySQL to Protobuf.', 'mysql-to-protobuf', true, 381, '/tools/mysql-to-protobuf', 'MySQL', false, false),
  ('mysql-to-qlik', 'MySQL to Qlik', 'Convert MySQL to Qlik.', 'mysql-to-qlik', true, 382, '/tools/mysql-to-qlik', 'MySQL', false, false),
  ('mysql-to-rdataframe', 'MySQL to R DataFrame', 'Convert MySQL to R DataFrame.', 'mysql-to-rdataframe', true, 383, '/tools/mysql-to-rdataframe', 'MySQL', false, false),
  ('mysql-to-rdf', 'MySQL to RDF', 'Convert MySQL to RDF.', 'mysql-to-rdf', true, 384, '/tools/mysql-to-rdf', 'MySQL', false, false),
  ('mysql-to-restructuredtext', 'MySQL to reStructuredText', 'Convert MySQL to reStructuredText.', 'mysql-to-restructuredtext', true, 385, '/tools/mysql-to-restructuredtext', 'MySQL', false, false),
  ('mysql-to-ruby', 'MySQL to Ruby', 'Convert MySQL to Ruby.', 'mysql-to-ruby', true, 386, '/tools/mysql-to-ruby', 'MySQL', false, false),
  ('mysql-to-sql', 'MySQL to SQL', 'Format/Clean MySQL.', 'mysql-to-sql', true, 387, '/tools/mysql-to-sql', 'MySQL', false, false),
  ('mysql-to-textile', 'MySQL to Textile', 'Convert MySQL to Textile.', 'mysql-to-textile', true, 388, '/tools/mysql-to-textile', 'MySQL', false, false),
  ('mysql-to-toml', 'MySQL to TOML', 'Convert MySQL to TOML.', 'mysql-to-toml', true, 389, '/tools/mysql-to-toml', 'MySQL', false, false),
  ('mysql-to-tracwiki', 'MySQL to TracWiki', 'Convert MySQL to TracWiki.', 'mysql-to-tracwiki', true, 390, '/tools/mysql-to-tracwiki', 'MySQL', false, false),
  ('mysql-to-xml', 'MySQL to XML', 'Convert MySQL to XML.', 'mysql-to-xml', true, 391, '/tools/mysql-to-xml', 'MySQL', false, false),
  ('mysql-to-yaml', 'MySQL to YAML', 'Convert MySQL to YAML.', 'mysql-to-yaml', true, 392, '/tools/mysql-to-yaml', 'MySQL', false, false),
  ('mediawiki-to-actionscript', 'MediaWiki to ActionScript', 'Convert MediaWiki to ActionScript.', 'mediawiki-to-actionscript', true, 393, '/tools/mediawiki-to-actionscript', 'MediaWiki', false, false),
  ('mediawiki-to-ascii', 'MediaWiki to ASCII', 'Convert MediaWiki to ASCII.', 'mediawiki-to-ascii', true, 394, '/tools/mediawiki-to-ascii', 'MediaWiki', false, false),
  ('mediawiki-to-asciidoc', 'MediaWiki to AsciiDoc', 'Convert MediaWiki to AsciiDoc.', 'mediawiki-to-asciidoc', true, 395, '/tools/mediawiki-to-asciidoc', 'MediaWiki', false, false),
  ('mediawiki-to-asp', 'MediaWiki to ASP', 'Convert MediaWiki to ASP.', 'mediawiki-to-asp', true, 396, '/tools/mediawiki-to-asp', 'MediaWiki', false, false),
  ('mediawiki-to-avro', 'MediaWiki to Avro', 'Convert MediaWiki to Avro.', 'mediawiki-to-avro', true, 397, '/tools/mediawiki-to-avro', 'MediaWiki', false, false),
  ('mediawiki-to-bbcode', 'MediaWiki to BBCode', 'Convert MediaWiki to BBCode.', 'mediawiki-to-bbcode', true, 398, '/tools/mediawiki-to-bbcode', 'MediaWiki', false, false),
  ('mediawiki-to-csv', 'MediaWiki to CSV', 'Convert MediaWiki to CSV.', 'mediawiki-to-csv', true, 399, '/tools/mediawiki-to-csv', 'MediaWiki', false, false),
  ('mediawiki-to-dax', 'MediaWiki to DAX', 'Convert MediaWiki to DAX.', 'mediawiki-to-dax', true, 400, '/tools/mediawiki-to-dax', 'MediaWiki', false, false),
  ('mediawiki-to-excel', 'MediaWiki to Excel', 'Convert MediaWiki to Excel.', 'mediawiki-to-excel', true, 401, '/tools/mediawiki-to-excel', 'MediaWiki', false, false),
  ('mediawiki-to-firebase', 'MediaWiki to Firebase', 'Convert MediaWiki to Firebase.', 'mediawiki-to-firebase', true, 402, '/tools/mediawiki-to-firebase', 'MediaWiki', false, false),
  ('mediawiki-to-html', 'MediaWiki to HTML', 'Convert MediaWiki to HTML.', 'mediawiki-to-html', true, 403, '/tools/mediawiki-to-html', 'MediaWiki', false, false),
  ('mediawiki-to-ini', 'MediaWiki to INI', 'Convert MediaWiki to INI.', 'mediawiki-to-ini', true, 404, '/tools/mediawiki-to-ini', 'MediaWiki', false, false),
  ('mediawiki-to-jira', 'MediaWiki to Jira', 'Convert MediaWiki to Jira.', 'mediawiki-to-jira', true, 405, '/tools/mediawiki-to-jira', 'MediaWiki', false, false),
  ('mediawiki-to-jpeg', 'MediaWiki to JPEG', 'Convert MediaWiki to JPEG (Image).', 'mediawiki-to-jpeg', true, 406, '/tools/mediawiki-to-jpeg', 'MediaWiki', false, false),
  ('mediawiki-to-json', 'MediaWiki to JSON', 'Convert MediaWiki to JSON.', 'mediawiki-to-json', true, 407, '/tools/mediawiki-to-json', 'MediaWiki', false, false),
  ('mediawiki-to-jsonlines', 'MediaWiki to JSON Lines', 'Convert MediaWiki to JSON Lines.', 'mediawiki-to-jsonlines', true, 408, '/tools/mediawiki-to-jsonlines', 'MediaWiki', false, false),
  ('mediawiki-to-latex', 'MediaWiki to LaTeX', 'Convert MediaWiki to LaTeX.', 'mediawiki-to-latex', true, 409, '/tools/mediawiki-to-latex', 'MediaWiki', false, false),
  ('mediawiki-to-magic', 'MediaWiki to Magic', 'Convert MediaWiki to Magic.', 'mediawiki-to-magic', true, 410, '/tools/mediawiki-to-magic', 'MediaWiki', false, false),
  ('mediawiki-to-markdown', 'MediaWiki to Markdown', 'Convert MediaWiki to Markdown.', 'mediawiki-to-markdown', true, 411, '/tools/mediawiki-to-markdown', 'MediaWiki', false, false),
  ('mediawiki-to-matlab', 'MediaWiki to MATLAB', 'Convert MediaWiki to MATLAB.', 'mediawiki-to-matlab', true, 412, '/tools/mediawiki-to-matlab', 'MediaWiki', false, false),
  ('mediawiki-to-mediawiki', 'MediaWiki to MediaWiki', 'Format/Beautify MediaWiki.', 'mediawiki-to-mediawiki', true, 413, '/tools/mediawiki-to-mediawiki', 'MediaWiki', false, false),
  ('mediawiki-to-pandasdataframe', 'MediaWiki to Pandas', 'Convert MediaWiki to Pandas.', 'mediawiki-to-pandasdataframe', true, 414, '/tools/mediawiki-to-pandasdataframe', 'MediaWiki', false, false),
  ('mediawiki-to-pdf', 'MediaWiki to PDF', 'Convert MediaWiki to PDF.', 'mediawiki-to-pdf', true, 415, '/tools/mediawiki-to-pdf', 'MediaWiki', false, false),
  ('mediawiki-to-php', 'MediaWiki to PHP', 'Convert MediaWiki to PHP.', 'mediawiki-to-php', true, 416, '/tools/mediawiki-to-php', 'MediaWiki', false, false),
  ('mediawiki-to-png', 'MediaWiki to PNG', 'Convert MediaWiki to PNG (Image).', 'mediawiki-to-png', true, 417, '/tools/mediawiki-to-png', 'MediaWiki', false, false),
  ('mediawiki-to-protobuf', 'MediaWiki to Protobuf', 'Convert MediaWiki to Protobuf.', 'mediawiki-to-protobuf', true, 418, '/tools/mediawiki-to-protobuf', 'MediaWiki', false, false),
  ('mediawiki-to-qlik', 'MediaWiki to Qlik', 'Convert MediaWiki to Qlik.', 'mediawiki-to-qlik', true, 419, '/tools/mediawiki-to-qlik', 'MediaWiki', false, false),
  ('mediawiki-to-rdataframe', 'MediaWiki to R DataFrame', 'Convert MediaWiki to R DataFrame.', 'mediawiki-to-rdataframe', true, 420, '/tools/mediawiki-to-rdataframe', 'MediaWiki', false, false),
  ('mediawiki-to-rdf', 'MediaWiki to RDF', 'Convert MediaWiki to RDF.', 'mediawiki-to-rdf', true, 421, '/tools/mediawiki-to-rdf', 'MediaWiki', false, false),
  ('mediawiki-to-restructuredtext', 'MediaWiki to reStructuredText', 'Convert MediaWiki to reStructuredText.', 'mediawiki-to-restructuredtext', true, 422, '/tools/mediawiki-to-restructuredtext', 'MediaWiki', false, false),
  ('mediawiki-to-ruby', 'MediaWiki to Ruby', 'Convert MediaWiki to Ruby.', 'mediawiki-to-ruby', true, 423, '/tools/mediawiki-to-ruby', 'MediaWiki', false, false),
  ('mediawiki-to-sql', 'MediaWiki to SQL', 'Convert MediaWiki to SQL.', 'mediawiki-to-sql', true, 424, '/tools/mediawiki-to-sql', 'MediaWiki', false, false),
  ('mediawiki-to-textile', 'MediaWiki to Textile', 'Convert MediaWiki to Textile.', 'mediawiki-to-textile', true, 425, '/tools/mediawiki-to-textile', 'MediaWiki', false, false),
  ('mediawiki-to-toml', 'MediaWiki to TOML', 'Convert MediaWiki to TOML.', 'mediawiki-to-toml', true, 426, '/tools/mediawiki-to-toml', 'MediaWiki', false, false),
  ('mediawiki-to-tracwiki', 'MediaWiki to TracWiki', 'Convert MediaWiki to TracWiki.', 'mediawiki-to-tracwiki', true, 427, '/tools/mediawiki-to-tracwiki', 'MediaWiki', false, false),
  ('mediawiki-to-xml', 'MediaWiki to XML', 'Convert MediaWiki to XML.', 'mediawiki-to-xml', true, 428, '/tools/mediawiki-to-xml', 'MediaWiki', false, false),
  ('mediawiki-to-yaml', 'MediaWiki to YAML', 'Convert MediaWiki to YAML.', 'mediawiki-to-yaml', true, 429, '/tools/mediawiki-to-yaml', 'MediaWiki', false, false)
ON CONFLICT (key) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order,
  href = EXCLUDED.href,
  category = EXCLUDED.category,
  is_new = EXCLUDED.is_new,
  is_popular = EXCLUDED.is_popular,
  updated_at = now();
